package at.mschreiber.adventofcode.day21;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Day21Exercise2 {
  static Map<String, String> monkeys = new HashMap<String, String>();

  public static void main(String[] args) {
    String[] lines = input.split("\r\n");
    for (String line : lines) {
      monkeys.put(line.split(":")[0], line.split(":")[1].trim());
    }

    // the "humn" is not in this path, so the value should not change
    long valueB = numberOfMonkey(monkeys.get("root").split(" ")[2], 0);
    long low = 0;
    long high = (long) Math.pow(10, 15); // "random" high number, Long.MAX_VALUE does not work, since the math
                                         // operations done in the code input does then exeed the max value
    long score = 0;
    String monkey = monkeys.get("root").split(" ")[0];
    long mid = 0;
    while (low < high) {
      mid = Math.floorDiv((low + high), 2);
      score = valueB - numberOfMonkey(monkey, mid);
      if (score < 0) {
        low = mid;
      }
      if (score == 0) {
        System.out.println("Found: " + mid);
        break;
      }
      if (score > 0) {
        high = mid;
      }
    }
  }

  public static long numberOfMonkey(String monkey, long x) {
    if ("humn".equals(monkey) && x >= 0) {
      return x;
    }
    String a = monkeys.get(monkey);
    try {
      long xx = Long.parseLong(a);
      return xx;
    } catch (NumberFormatException e) {

    }
    long valueA = numberOfMonkey(a.split(" ")[0], x);
    long valueB = numberOfMonkey(a.split(" ")[2], x);
    String operation = a.split(" ")[1];
    if ("-".equals(operation)) {
      return valueA - valueB;
    }
    if ("+".equals(operation)) {
      return valueA + valueB;
    }
    if ("*".equals(operation)) {
      return valueA * valueB;
    }
    if ("/".equals(operation)) {
      return valueA / valueB;
    }
    System.out.println("Should not be here!!");
    return 0;
  }

  public static String input = "sdmf: gbvc * gvmh\r\n" + "czpt: 5\r\n" + "jzcm: 2\r\n" + "qntt: wtdg - gnpc\r\n"
      + "vfvp: hwqp / dnnz\r\n" + "bfsf: vvrq - bpdc\r\n" + "fvjh: cfmh * twfn\r\n" + "pmqg: vffz * qrzr\r\n"
      + "fgsj: szzp * mtml\r\n" + "pltc: vgqg * shzb\r\n" + "tfmp: nqqc * bjht\r\n" + "chdw: 3\r\n"
      + "frgv: rwpq * qnhv\r\n" + "mfmr: vlgs * rtbd\r\n" + "ldmt: 2\r\n" + "tbql: 5\r\n" + "jqbg: 19\r\n"
      + "jfrw: cwcn * gjjq\r\n" + "qwjf: ghrq * jhnh\r\n" + "htzp: wvst * ldtg\r\n" + "cwcn: 2\r\n" + "fcbp: 4\r\n"
      + "ljmw: 10\r\n" + "zgwz: 7\r\n" + "fbvz: 2\r\n" + "lvbz: jdss + jdbg\r\n" + "zgqj: pslb * tgqf\r\n"
      + "szzp: 5\r\n" + "nhdg: vfsr + vfhs\r\n" + "wltj: bvvb * vdht\r\n" + "mdmh: 2\r\n" + "mftg: vmtl * lptl\r\n"
      + "jdss: ljbw + hnqq\r\n" + "tbfs: smbs + crtb\r\n" + "ftsh: 4\r\n" + "grrg: 2\r\n" + "rrcq: 10\r\n"
      + "rvwf: 3\r\n" + "ggtf: 5\r\n" + "plgl: gvnb - wzdv\r\n" + "rczs: 4\r\n" + "djlt: 5\r\n"
      + "cbnt: tvlf * jbmc\r\n" + "strq: wqgv * cldl\r\n" + "rphc: vnwg + rptv\r\n" + "pscr: 3\r\n" + "jpnf: 2\r\n"
      + "mdwr: mrzn - zdhl\r\n" + "rwwq: dlzc / fprn\r\n" + "bnmm: qstf * npnm\r\n" + "rgzp: jtwz * rmtc\r\n"
      + "mtpg: 2\r\n" + "jfbs: mjlr * ngbn\r\n" + "cngm: 2\r\n" + "dgsv: 2\r\n" + "rjlc: hchh * rhgn\r\n"
      + "pvsf: 2\r\n" + "zgss: 2\r\n" + "vddj: nqrj * sttf\r\n" + "qfzt: qfdn + srtq\r\n" + "wdtn: qmvt / gsbf\r\n"
      + "nmfn: 3\r\n" + "dcch: 17\r\n" + "fzvn: 2\r\n" + "cfbd: 2\r\n" + "glzm: hvdw + nczt\r\n" + "nczt: 3\r\n"
      + "bfpf: dbmt * dfpp\r\n" + "tgsz: lnwr + nfjw\r\n" + "msjr: 14\r\n" + "mpcs: 5\r\n" + "cvtc: 4\r\n"
      + "fppq: slrn * lwmr\r\n" + "hfcm: gfdv * tpwn\r\n" + "sbfs: 4\r\n" + "smrl: 4\r\n" + "csbd: 5\r\n"
      + "qnzm: qvtj * thcd\r\n" + "swrr: 3\r\n" + "wjrz: 3\r\n" + "cgwq: bpqd / lvrl\r\n" + "tthj: 1\r\n"
      + "ffhc: jprv * cqvz\r\n" + "fmvg: 5\r\n" + "cldl: jnrv + dqlv\r\n" + "nzzz: 2\r\n" + "vwrd: 1\r\n"
      + "sfrz: 3\r\n" + "jnrv: hwzd * pscq\r\n" + "rrss: 2\r\n" + "ggvn: 15\r\n" + "mqgn: vgbq + scth\r\n"
      + "vvrq: tptb * tspq\r\n" + "wffw: 10\r\n" + "sbwp: 2\r\n" + "clrz: 6\r\n" + "tdgv: 4\r\n" + "rbds: 2\r\n"
      + "mlps: 3\r\n" + "rzvg: 4\r\n" + "bnhc: mdzc * tlfs\r\n" + "llfg: nfqr + twcf\r\n" + "vdbv: vvtn * zvbr\r\n"
      + "stpn: lmhg + ftpt\r\n" + "szmg: dpnh * lzwn\r\n" + "bnnd: 2\r\n" + "lqvn: vghs * mtwr\r\n" + "nfjn: 8\r\n"
      + "wqjm: tctl * jdcr\r\n" + "smbs: drsf - srwm\r\n" + "nrjd: 5\r\n" + "hllf: 16\r\n" + "mgms: tmht * cqgw\r\n"
      + "cwfh: 2\r\n" + "scwf: zphc * hlbw\r\n" + "srtn: zsgr * hmzq\r\n" + "ncsd: 10\r\n" + "spmc: vfpw - wwcj\r\n"
      + "gmjh: mzhm * zhbc\r\n" + "pgpp: 14\r\n" + "bdbh: lcfh * gbwh\r\n" + "nsll: mvjq + sgnv\r\n" + "wrrj: 2\r\n"
      + "lbgt: 2\r\n" + "jspg: lwmf * lcwh\r\n" + "smnn: 5\r\n" + "cvws: qpwg + qprb\r\n" + "dbmt: vwzw * llhh\r\n"
      + "rmdw: 4\r\n" + "czvc: pmsq * mnms\r\n" + "sdsz: lppc * vqbd\r\n" + "bqdp: 2\r\n" + "wzdv: jpqm * rrcq\r\n"
      + "dqbh: 2\r\n" + "znjh: 2\r\n" + "jdbg: dwdp * hwtm\r\n" + "pzcl: 1\r\n" + "bzrm: 2\r\n" + "mbbz: 17\r\n"
      + "sqgn: vhqz * hzwt\r\n" + "pmlz: 3\r\n" + "zfsz: 8\r\n" + "vhqz: 2\r\n" + "dcdl: flnp + fnmp\r\n"
      + "djwj: 2\r\n" + "zfwb: 3\r\n" + "vgmv: 3\r\n" + "fwgq: tjmt + mgwm\r\n" + "tpqj: pwsw * wjrn\r\n"
      + "vtth: 7\r\n" + "vtzl: 12\r\n" + "gphr: qrng * dlrn\r\n" + "qwtc: 1\r\n" + "pfhr: 2\r\n" + "mlpw: 11\r\n"
      + "lqgq: 7\r\n" + "vdwv: bwvs * bgnn\r\n" + "jjbd: rqbf - vjsb\r\n" + "twgq: 15\r\n" + "vffz: 3\r\n"
      + "dmgm: fnvh + cnfv\r\n" + "qbjc: vwhs + zvmg\r\n" + "zvnl: 2\r\n" + "bgtv: rtjr * pcgj\r\n"
      + "wqtp: vgjl + bwft\r\n" + "hmzs: lsvq + vgtd\r\n" + "nmbw: tptl - hbtz\r\n" + "qbjj: 2\r\n" + "qpwg: 9\r\n"
      + "cqpg: 5\r\n" + "qvdn: zllh - pprn\r\n" + "hmtj: 1\r\n" + "mhgp: tlbh * mpcs\r\n" + "djtb: zzpt + fsjz\r\n"
      + "snqf: 4\r\n" + "hgtt: jwms - czsn\r\n" + "zzlt: fvjn * dwdq\r\n" + "fnmp: pcqj / rpvt\r\n" + "vlgs: 14\r\n"
      + "vzsj: bvll / mflt\r\n" + "gwwq: hrzg + wqnb\r\n" + "hhmw: 2\r\n" + "lfgf: zsgv * ldzv\r\n" + "qrzr: 3\r\n"
      + "nzzw: qhdt + lplj\r\n" + "qqsz: 2\r\n" + "vbwq: 2\r\n" + "hfjr: cmwt + ztwq\r\n" + "ddhr: 2\r\n"
      + "cmth: qntt * sntj\r\n" + "dncm: svgw * jrgc\r\n" + "sfqg: 6\r\n" + "dlzc: trfn * qctj\r\n"
      + "hrsh: bzbj * hlzg\r\n" + "wjzt: hblg + fjqb\r\n" + "hglp: 11\r\n" + "qhlw: sblc * zrzs\r\n" + "gzgt: 9\r\n"
      + "wftr: 2\r\n" + "htbw: 3\r\n" + "dpct: 4\r\n" + "wsjr: tncf - cqpg\r\n" + "jlwn: 18\r\n"
      + "wvgv: chdw * dnvl\r\n" + "dwdq: 14\r\n" + "rjqp: 4\r\n" + "wrcz: strq + ntlb\r\n" + "gmmr: djll + lpjh\r\n"
      + "fnvh: bjbf + bcrh\r\n" + "tsqp: 3\r\n" + "cjcs: mjts / lqcm\r\n" + "thnb: jsns * gfts\r\n" + "rpql: 2\r\n"
      + "wvfg: 9\r\n" + "dzjp: 4\r\n" + "grmz: hnlq * hnmn\r\n" + "npjw: 5\r\n" + "gmmd: zvvb + wrvq\r\n"
      + "mjpp: hbtq * hgnb\r\n" + "bqvf: dvwr - mmlz\r\n" + "ttrr: 5\r\n" + "ptmq: 8\r\n" + "wbdh: 3\r\n"
      + "gljn: qjgj * gtds\r\n" + "dpzb: wdnv + jpcd\r\n" + "mnsl: bwbd * pwpv\r\n" + "ldzv: 3\r\n"
      + "tltc: wjhg * gwcr\r\n" + "gndz: 3\r\n" + "znnw: pshv * gjbf\r\n" + "hbfc: 2\r\n" + "ljtw: 5\r\n"
      + "mhcv: jqvd * ncrl\r\n" + "jgrj: vnsv * prrl\r\n" + "jjrv: 5\r\n" + "gfdv: fjfw / fbvz\r\n"
      + "mjjr: mnbl + hpjr\r\n" + "tjqn: vsfn + vshp\r\n" + "ndhm: 3\r\n" + "fnqg: 2\r\n" + "zqjj: 5\r\n"
      + "tqzc: 2\r\n" + "zsnh: gcbq / mzpl\r\n" + "fbvn: gcjz + fhdq\r\n" + "vftj: 4\r\n" + "pjmd: 2\r\n"
      + "fvcd: dmsh / lfqt\r\n" + "zwlf: 3\r\n" + "hssd: dtmh * phwn\r\n" + "dlrj: 3\r\n" + "lwst: 2\r\n"
      + "mjzq: pmqg * mflm\r\n" + "humn: 105\r\n" + "lqdc: 3\r\n" + "rnzm: llbt + thnb\r\n" + "pmhn: 4\r\n"
      + "dfmv: 3\r\n" + "hvmf: srgn + sgqm\r\n" + "mlgt: wbtw + jqcr\r\n" + "wllc: qhqh + hznv\r\n"
      + "hfth: frhs * nghl\r\n" + "wjhg: 7\r\n" + "lrrc: 14\r\n" + "mrrb: 3\r\n" + "jfjm: jpfg * qwpt\r\n"
      + "wvpp: fnln * qctr\r\n" + "nwfz: 2\r\n" + "mdds: zrwp * wtwq\r\n" + "vfsr: qvtg * dvcn\r\n" + "jcvf: 5\r\n"
      + "lhjt: 2\r\n" + "zlfb: 5\r\n" + "zfnl: tjfn + pwgh\r\n" + "hhpr: zjcd - qgnz\r\n" + "srfc: rdmd * ggsg\r\n"
      + "fcdg: 5\r\n" + "hlnv: hbzr - pmhh\r\n" + "gvwq: 2\r\n" + "gwhf: 2\r\n" + "ntcq: fthn + rrtr\r\n"
      + "jqzb: pfvw * rncq\r\n" + "zmdj: pcwh * lhjt\r\n" + "dgwd: 3\r\n" + "cvwg: cdwq + rhdg\r\n"
      + "pgrb: zvgv * jvcs\r\n" + "dzrf: 3\r\n" + "fmjp: zlrf / rgvd\r\n" + "nltt: jcvn * tctc\r\n"
      + "bbtw: fppq + vrjq\r\n" + "wgjr: ljgl / lpnt\r\n" + "scrj: 2\r\n" + "qhnn: gvqp + jspv\r\n" + "flfv: 5\r\n"
      + "jljf: brjm + wqtp\r\n" + "qpzm: qscr / dmzl\r\n" + "rvrd: wzmz / zhst\r\n" + "swgh: 4\r\n" + "jzml: 4\r\n"
      + "sqvc: 8\r\n" + "bpqd: pggq + lfvc\r\n" + "lhcb: 9\r\n" + "cgdl: spcg - zfvf\r\n" + "cflb: 5\r\n"
      + "mdnw: 4\r\n" + "vcft: 5\r\n" + "lqtt: fsmc * lwbw\r\n" + "vzmp: 1\r\n" + "fdpc: 7\r\n"
      + "csgn: frdv + tcsq\r\n" + "dggf: jglj * dzqd\r\n" + "ltmn: tttn * gcbn\r\n" + "gbgm: cqpw + thlb\r\n"
      + "jqvd: 2\r\n" + "zgpz: 6\r\n" + "cbsj: fwwm + fgwt\r\n" + "chjs: 1\r\n" + "qpcp: 1\r\n"
      + "lwmr: fvrd - slrs\r\n" + "vzwv: zrwm + gdnh\r\n" + "rpzr: 5\r\n" + "qtvf: sznc + flrl\r\n"
      + "zjcd: pdwq * rlrs\r\n" + "tcdf: fdls / vzmj\r\n" + "vbsn: wvgv + qwjb\r\n" + "wtpr: pgsr + clsg\r\n"
      + "fstr: 3\r\n" + "hgmg: 12\r\n" + "vtcg: 5\r\n" + "vmmd: 9\r\n" + "vlnd: 3\r\n" + "lgqg: tvsd - slvg\r\n"
      + "vpsd: 2\r\n" + "tzws: wvsq + tnzd\r\n" + "vtwv: 3\r\n" + "qddv: humn + fpwf\r\n" + "zhhs: 2\r\n"
      + "rglf: 4\r\n" + "mppv: nptf * sdml\r\n" + "bfsb: lfhj * fhct\r\n" + "snzv: 2\r\n" + "qqvv: cdzs - tjqh\r\n"
      + "zhbc: 4\r\n" + "jcgq: lmzr - rbbt\r\n" + "qvtg: 3\r\n" + "zvrf: bjwr - zszw\r\n" + "vwmb: 6\r\n"
      + "fnwt: htmr + cdpp\r\n" + "thch: fpsl + dmgm\r\n" + "mttn: 2\r\n" + "hzwt: wwqp + pppg\r\n"
      + "hbzr: dwcr * htzw\r\n" + "grvf: cfcn + jjqv\r\n" + "zlch: 3\r\n" + "wdcf: 2\r\n" + "lzds: 11\r\n"
      + "nphv: 5\r\n" + "llqg: 3\r\n" + "wrvq: 7\r\n" + "nmqp: dnhv * hjvq\r\n" + "bjwm: 2\r\n" + "mndb: 2\r\n"
      + "cjwc: 3\r\n" + "dszw: mgbl * blrj\r\n" + "nfpb: gfsp * hdrs\r\n" + "drtp: 5\r\n" + "tqgz: fwqm * ftsh\r\n"
      + "hbhf: 2\r\n" + "zttd: 13\r\n" + "jgcz: 8\r\n" + "dgnr: 3\r\n" + "sglf: pgcv / pfch\r\n" + "spwb: 1\r\n"
      + "srrw: hddc / wftr\r\n" + "pcdc: bpvv * zwgv\r\n" + "zbqr: 6\r\n" + "smrt: fjlw * rrvr\r\n" + "wtfr: 3\r\n"
      + "scsl: 9\r\n" + "vdql: pngh * ztjw\r\n" + "cdwm: 5\r\n" + "vsrv: cgmc - shjz\r\n" + "fpzt: stpn * vbpj\r\n"
      + "qhdt: bcjf * cgdl\r\n" + "jrpg: 11\r\n" + "rzjh: 17\r\n" + "gwvb: 1\r\n" + "hfzc: 5\r\n" + "mpfd: 1\r\n"
      + "gfts: ljfh - jbrh\r\n" + "psvp: 1\r\n" + "tmfz: jmfd * ftqd\r\n" + "ntzh: 3\r\n" + "wpwl: 7\r\n"
      + "pzsc: tdng * wmzm\r\n" + "lmld: nfbh + clrz\r\n" + "qstf: 3\r\n" + "bsct: dmfh * bhtn\r\n" + "bsbj: 4\r\n"
      + "jfch: wmfz * bstr\r\n" + "smjq: 2\r\n" + "lcfh: rrtg + bgqv\r\n" + "dtsj: vlrp + mzdb\r\n"
      + "ttpl: flhb * zdhq\r\n" + "pzmc: qwlg + frpp\r\n" + "blsp: 6\r\n" + "pqcf: stdg + pmnq\r\n" + "ltwz: 11\r\n"
      + "chnv: 2\r\n" + "rdzw: cllm - mqss\r\n" + "sttf: 2\r\n" + "hfvr: 2\r\n" + "bnvc: 2\r\n" + "cgqd: 3\r\n"
      + "lgdc: 17\r\n" + "rbhd: zcwd + zbqc\r\n" + "lfpz: 5\r\n" + "mjsq: 3\r\n" + "jsjh: 11\r\n" + "mnrg: 2\r\n"
      + "trwz: wmjb + zbwr\r\n" + "bwwj: 2\r\n" + "vqjz: 10\r\n" + "rptv: wgtz + tmmd\r\n" + "tmfs: 2\r\n"
      + "tptb: 3\r\n" + "sgqm: brjd * pzvh\r\n" + "jqrb: vbwv + fbcn\r\n" + "jjpp: dtsj * fmrz\r\n" + "gcjm: 2\r\n"
      + "mqmp: 8\r\n" + "fbnp: 5\r\n" + "mzhm: qlbt * lzjp\r\n" + "vrrt: 2\r\n" + "mwtl: gwmr * rnlp\r\n"
      + "vhhz: 6\r\n" + "wssm: qqln * lnbh\r\n" + "grzd: 2\r\n" + "pfch: 2\r\n" + "pvsh: jfnb / mdmh\r\n"
      + "gfwm: 3\r\n" + "fdwr: pgnw + glph\r\n" + "zblv: rgzp * thns\r\n" + "bfwb: 4\r\n" + "mtdl: gcwq + plgl\r\n"
      + "gwmr: 3\r\n" + "pthq: bnnd * qqqm\r\n" + "nhmn: 2\r\n" + "vgcj: 2\r\n" + "fwqm: 2\r\n"
      + "ncrs: blnw - hrfj\r\n" + "qsjj: pmzn * tbql\r\n" + "hcfb: smvb * ftgt\r\n" + "vzmj: 5\r\n" + "tvrh: 4\r\n"
      + "rrtr: 1\r\n" + "smtf: qtmc / jlbb\r\n" + "vnvm: jfbs + mfrg\r\n" + "tbqn: 3\r\n" + "mfjg: mhgp / dpln\r\n"
      + "vfft: 3\r\n" + "mgws: llzh * pjss\r\n" + "fjfw: wtdq * lggn\r\n" + "dgjq: 8\r\n" + "qpbj: 12\r\n"
      + "zvlt: 5\r\n" + "qdtq: vwwr * mzff\r\n" + "bcsf: ngrq + srdv\r\n" + "zpwf: shlc / dqjv\r\n" + "wzmw: 2\r\n"
      + "rfgp: zpbq * scrj\r\n" + "cbnb: 17\r\n" + "rgvd: 2\r\n" + "dbzf: zvwd + sfdz\r\n" + "ssrj: dbqc / mrld\r\n"
      + "zbqc: 3\r\n" + "sjzt: ftnr / zmlz\r\n" + "wtsl: 2\r\n" + "pdjf: bdgv + hmcr\r\n" + "gwcl: wbdh * dfqj\r\n"
      + "ghtr: 11\r\n" + "gbqm: 11\r\n" + "vwhs: fbbs * tqzc\r\n" + "nvhn: 7\r\n" + "pljh: 6\r\n"
      + "cndq: tgmr * pzrf\r\n" + "dpwf: zgpz * tfzg\r\n" + "mhnp: 3\r\n" + "mcbr: 4\r\n" + "zvpt: 2\r\n"
      + "fjzm: crqc * mttn\r\n" + "ggrq: fsnz + bfng\r\n" + "pfzj: 5\r\n" + "zsgv: 2\r\n" + "tmnd: btqq / swgh\r\n"
      + "zzmw: 2\r\n" + "cntm: 2\r\n" + "htqn: 3\r\n" + "fnml: rldn * qthr\r\n" + "vcwq: 4\r\n" + "pfsw: 5\r\n"
      + "vhqf: gjvv + gwcl\r\n" + "gbhr: ghgb * njcp\r\n" + "stps: fwjj * rczs\r\n" + "nlpz: phqm * vgmv\r\n"
      + "hfgs: nzzz + tlmt\r\n" + "cfpj: 2\r\n" + "qchg: 5\r\n" + "cggh: zswh * ctbq\r\n" + "jjgl: 8\r\n"
      + "gjcl: 11\r\n" + "vqjg: 4\r\n" + "dhzh: qhlw + vhgv\r\n" + "ggtg: 4\r\n" + "mqfm: 2\r\n" + "gdsh: 5\r\n"
      + "dwtb: hlnv + zcdh\r\n" + "vtgg: 1\r\n" + "jpnb: djwh + ltlq\r\n" + "rmtl: 4\r\n" + "sjcl: vtth * wsld\r\n"
      + "bvtd: 5\r\n" + "mcnc: jsqw * zrzv\r\n" + "bmnj: 3\r\n" + "jdcr: 2\r\n" + "bgng: 2\r\n" + "gslm: 5\r\n"
      + "dmbg: 2\r\n" + "ppcv: 3\r\n" + "zcdh: cjgn * bqvf\r\n" + "fsts: dhbj * fbbq\r\n" + "hzfs: 5\r\n"
      + "lntf: 4\r\n" + "fdls: mmnh - wltj\r\n" + "vqmf: 2\r\n" + "drwh: 3\r\n" + "lpzm: qhzv + hpdz\r\n"
      + "ggpv: lzzz + cnfb\r\n" + "ggzz: fdrw + djmj\r\n" + "gnsp: 9\r\n" + "hjnl: lpzm + mlnh\r\n" + "bmws: 5\r\n"
      + "drcg: 6\r\n" + "gzmd: 5\r\n" + "sfpn: 2\r\n" + "swdq: 2\r\n" + "nntz: dmbg * hmsc\r\n"
      + "hpjr: jdrm + gjjr\r\n" + "vjmv: lvtt + ddsz\r\n" + "ctmd: rzrv / gzct\r\n" + "spwz: 2\r\n"
      + "fbbs: smrl + scvc\r\n" + "znsv: vbwq * ztgb\r\n" + "hdjf: 7\r\n" + "fbbq: 4\r\n" + "znrs: gmwb * mgjg\r\n"
      + "crvs: 3\r\n" + "rvcn: wtfr * mfmz\r\n" + "wqwc: hjfv * zgwz\r\n" + "jbvc: 2\r\n" + "mmnh: thch / cnbs\r\n"
      + "rlrs: 3\r\n" + "vnwg: twqp * fblr\r\n" + "dfjb: 2\r\n" + "cjwq: smtf + qsjv\r\n" + "qnsv: njvh * wjrz\r\n"
      + "vqcd: 2\r\n" + "mvnq: pgpp / dqbh\r\n" + "msrv: 16\r\n" + "dmzq: 2\r\n" + "wnpv: 15\r\n"
      + "cnbs: pgff * lcql\r\n" + "nbwv: 1\r\n" + "ldcr: 7\r\n" + "wqcc: 2\r\n" + "cmlf: 5\r\n"
      + "wzhh: gjfq * rmhh\r\n" + "ptnb: jfgl + bpfd\r\n" + "gjpr: 18\r\n" + "pwtl: tbfs + jcwp\r\n" + "qhzv: 11\r\n"
      + "zswh: mtrw * mmtd\r\n" + "vcqz: mzhs - bzpg\r\n" + "jltr: fdwr * drwh\r\n" + "snpt: njnh * mbnn\r\n"
      + "qfdn: tbgq * wsqv\r\n" + "sltc: hqgp * fffr\r\n" + "wldh: 4\r\n" + "rjvm: 4\r\n" + "vjhn: jbvf * nnnv\r\n"
      + "twfs: qtfs * jqsd\r\n" + "djwh: mjpp - zlmp\r\n" + "qqqm: hbfb + lnzl\r\n" + "gtsh: gchj / bdww\r\n"
      + "drqf: 7\r\n" + "bzzp: rlct * jntw\r\n" + "tmht: 2\r\n" + "bdwt: llfg / qmfw\r\n" + "plwg: 3\r\n"
      + "tpwn: 2\r\n" + "jrzf: 7\r\n" + "vhrm: 2\r\n" + "shwm: 3\r\n" + "vdht: mhnp * qfzv\r\n" + "lpcl: 3\r\n"
      + "hznv: tczj * pjlp\r\n" + "mzpl: 2\r\n" + "jwpq: npmn - dcdl\r\n" + "hpvh: 2\r\n" + "zlmp: 9\r\n"
      + "tlpf: mgqp * cjpm\r\n" + "ztjw: 8\r\n" + "ndfn: ttpl - bwzt\r\n" + "lctt: rdtm + jvrt\r\n"
      + "jpfg: tvdm + sbcv\r\n" + "zjzj: rfrm + mbff\r\n" + "glln: 3\r\n" + "fjhb: 5\r\n" + "qgvw: 7\r\n"
      + "dlrn: plrj + cflb\r\n" + "slrn: 2\r\n" + "vmtl: 3\r\n" + "nmvc: rrmt * bvqh\r\n" + "qfsf: vlzg * hdzl\r\n"
      + "mthd: tflc + ptnc\r\n" + "nrpc: 2\r\n" + "mzth: 3\r\n" + "lnmd: 4\r\n" + "fsnz: clgv - brnp\r\n"
      + "znrl: 5\r\n" + "fgpd: 18\r\n" + "zftv: 2\r\n" + "jhtv: bjwm * dhzh\r\n" + "dcbz: rsss / nrhc\r\n"
      + "nlnq: rdws * njrj\r\n" + "qqww: 2\r\n" + "qpsd: snzv * mflp\r\n" + "clgw: 11\r\n" + "tdfz: qznw - wdtn\r\n"
      + "jrzl: dmzq + btrl\r\n" + "jbdz: 20\r\n" + "pcqd: 3\r\n" + "hcts: rwgr * smnn\r\n" + "lzjp: 2\r\n"
      + "vshl: thfb + rdcj\r\n" + "qdft: 2\r\n" + "twfn: 2\r\n" + "cglv: gljn + bdwt\r\n" + "cfth: 3\r\n"
      + "jplp: nsll - qqww\r\n" + "frjj: pvtp * bdqv\r\n" + "zjjh: 3\r\n" + "vsrl: 2\r\n" + "rhdt: dqnf * smwd\r\n"
      + "zwrl: 1\r\n" + "zjjg: cvrf * ghtc\r\n" + "pjgm: ssmp + zzbg\r\n" + "cgtv: qdbn * hlrs\r\n"
      + "wfhf: jpnf * flnr\r\n" + "jtqg: wplz + nbvz\r\n" + "djrf: wlpw * mjsq\r\n" + "tvsd: mwrm - btcb\r\n"
      + "jmfd: mgbb + mdrw\r\n" + "glmn: 6\r\n" + "vfrb: 2\r\n" + "zzpt: ngmh * fmcc\r\n" + "dwjb: pthq - wjhh\r\n"
      + "pzvh: 3\r\n" + "wtdg: vgfg * jfqw\r\n" + "glrv: 2\r\n" + "wlpp: mjqp * qnhl\r\n" + "bssl: 2\r\n"
      + "smvb: hbhf + gjcl\r\n" + "vgbq: nfbt * zqgc\r\n" + "hlzg: pmcf * mrfw\r\n" + "gdcb: wgtd + chjs\r\n"
      + "twqp: cprt * zjjh\r\n" + "rvtp: vcvh + tjhb\r\n" + "rgvw: 2\r\n" + "rldn: 2\r\n" + "dvcn: rmbs * lmvs\r\n"
      + "mzff: mwfm + lhlc\r\n" + "slwh: mlps + zqsl\r\n" + "dcqn: 2\r\n" + "rldc: 2\r\n" + "cjbs: jjpp + tcbv\r\n"
      + "nlgb: 2\r\n" + "ttgq: dnjq * fztr\r\n" + "hwrd: vqrf * fzvn\r\n" + "gcbn: 3\r\n" + "sljt: qszj * nlgb\r\n"
      + "pprn: jrpp + bggf\r\n" + "hmsc: qdtw + hsht\r\n" + "dfwc: 5\r\n" + "zdjp: cscs * drvn\r\n"
      + "tzjq: ztrt / jgrj\r\n" + "qcqf: bwjw + bjwq\r\n" + "mvsn: 7\r\n" + "sjsh: wsjr + wfhf\r\n" + "glcj: 3\r\n"
      + "nbsg: vgnb * tfjp\r\n" + "vhtb: qcjn * ggvn\r\n" + "gdgs: znsv + zzmw\r\n" + "bjrg: lbnr * rjtd\r\n"
      + "ntlb: ndfn - tfrr\r\n" + "wnvp: hrjr * zpwf\r\n" + "vtgt: 3\r\n" + "qsmt: mdsv + pzzm\r\n"
      + "shlc: pjfb * cbjw\r\n" + "vgjn: rldc * zhrc\r\n" + "lnzl: czdr * bsgh\r\n" + "mptj: tcwn * hhlg\r\n"
      + "glcq: 11\r\n" + "bhtn: 3\r\n" + "gclq: hmzs * fqps\r\n" + "mfrg: zbtw * vtwv\r\n" + "bgbf: cvff * lctz\r\n"
      + "gnbz: tqsf * wqjm\r\n" + "zzbg: nhbc + nmlc\r\n" + "jzlh: 7\r\n" + "pwsd: 6\r\n" + "pmfg: gmtm * nvmr\r\n"
      + "tmrh: 2\r\n" + "zllh: tmrh * gclq\r\n" + "cwzm: tdnf - zqms\r\n" + "rvhd: 9\r\n" + "wnjq: 3\r\n"
      + "wwnp: 7\r\n" + "chqt: 16\r\n" + "llbt: pqhl + qdsv\r\n" + "cmrl: fwjs + cnph\r\n" + "qhqh: dmff - gltt\r\n"
      + "ncbr: znnw / vmvp\r\n" + "hvlq: 2\r\n" + "sqbs: 18\r\n" + "sqts: 5\r\n" + "wqfq: qzqh / gnbg\r\n"
      + "hpdz: ggfp * bgzm\r\n" + "sdml: 3\r\n" + "lmnb: 3\r\n" + "gpsq: slwh * mfds\r\n" + "mjqp: nwlm + ftjp\r\n"
      + "fzpl: lqvn / mqfm\r\n" + "qlmf: stdl / tsqp\r\n" + "wqsn: 7\r\n" + "qwmz: 5\r\n" + "hpzv: gvrg - tbvv\r\n"
      + "hqpz: vtgt + dbmz\r\n" + "pgbh: 2\r\n" + "vnsv: 4\r\n" + "gmph: cjwq + zhlt\r\n" + "pphv: 1\r\n"
      + "nhbc: 7\r\n" + "jhmn: 20\r\n" + "rcrc: hhcg * hjst\r\n" + "tnmb: dbqq * cdwc\r\n" + "jcvn: 4\r\n"
      + "chvz: qznc * jscj\r\n" + "nndq: 19\r\n" + "tqqs: qqvq + qwpj\r\n" + "fqrt: nvhn * vgcj\r\n" + "plrj: 2\r\n"
      + "bdgv: ggql * dcqn\r\n" + "nstg: fntd * nsvt\r\n" + "cfcn: 3\r\n" + "vhsh: gdgs + nzzw\r\n"
      + "rvbr: cvzl + wnjq\r\n" + "qvjz: 2\r\n" + "thpm: dggf * hnpv\r\n" + "qvtj: sjzt * tlqc\r\n"
      + "qgcp: mlpm + gdsh\r\n" + "cfmh: qwdn / lcnj\r\n" + "tlbh: fnbt + vcvv\r\n" + "wzvh: 8\r\n"
      + "mvlm: lvbz * lhwr\r\n" + "mtln: 3\r\n" + "qthr: fqzg - ggzn\r\n" + "bjbq: 5\r\n" + "jfqh: hcsc + jgmt\r\n"
      + "llzs: 5\r\n" + "hhbw: 4\r\n" + "bqpz: czvc + ppvs\r\n" + "whjc: 2\r\n" + "flnp: gzpd * tvrh\r\n"
      + "ftjp: 4\r\n" + "zrlg: 3\r\n" + "vrpz: vwrd + gslz\r\n" + "shpb: 4\r\n" + "zdfh: 2\r\n"
      + "dmrv: fnqg + qgcp\r\n" + "lsls: 12\r\n" + "qtfn: 5\r\n" + "dssw: 5\r\n" + "llsj: 9\r\n"
      + "qgzc: ztdb + cgsb\r\n" + "dzhg: 19\r\n" + "svvn: zmpn + dwjb\r\n" + "bblv: 3\r\n" + "zrwm: bhzh * nztf\r\n"
      + "fvrd: dgjm / pcqd\r\n" + "nwlj: 3\r\n" + "dfbp: 5\r\n" + "whqq: 8\r\n" + "nsbc: 2\r\n"
      + "fmfq: jnlw * whsh\r\n" + "dlrc: 5\r\n" + "wdnv: 2\r\n" + "llhn: 5\r\n" + "wfdp: vmdn + drtb\r\n"
      + "root: bjgs + tjtt\r\n" + "hzjw: 3\r\n" + "gwbq: 2\r\n" + "nbsj: 2\r\n" + "hbgz: gbzj * lqgq\r\n"
      + "pwsw: 5\r\n" + "qlcb: 2\r\n" + "wnjd: 3\r\n" + "bfbf: pjjm + wvnd\r\n" + "fbvw: vtfr + gddv\r\n"
      + "vzcn: 1\r\n" + "ssjl: crvt / qwmz\r\n" + "qhhc: 2\r\n" + "tmhw: 4\r\n" + "tnvc: tnmb * jtrr\r\n"
      + "mvhq: 13\r\n" + "zszw: 14\r\n" + "fwwm: pnbv * vsrl\r\n" + "qqln: 5\r\n" + "bfpp: 17\r\n" + "zqsl: 3\r\n"
      + "svzw: pnvw * sqts\r\n" + "lzwn: 3\r\n" + "jvqg: 2\r\n" + "mmdm: vcfr + rhvb\r\n" + "gnhh: 7\r\n"
      + "rdmd: 3\r\n" + "rbbt: nvrd * vmhz\r\n" + "dpwn: 3\r\n" + "cmpt: blcp - ddfl\r\n" + "tppw: 5\r\n"
      + "cpcz: zwlf * wszc\r\n" + "vqwm: 2\r\n" + "hdzl: 3\r\n" + "jhqz: wzvh * qfdw\r\n" + "ftpt: 8\r\n"
      + "pzrf: 14\r\n" + "jhqv: 3\r\n" + "btcb: 3\r\n" + "rjtd: jwpc + cbbc\r\n" + "rzrv: lgns * rvhc\r\n"
      + "rrcn: 4\r\n" + "jsns: ftrm + zmtn\r\n" + "qvth: vdbv + vdhp\r\n" + "jgwv: pgbh * pcmv\r\n" + "crpg: 2\r\n"
      + "mntv: 4\r\n" + "qwjs: dgsv * sbrg\r\n" + "htgs: 4\r\n" + "gfsp: whsb * tcsr\r\n" + "fzvm: 4\r\n"
      + "hlrs: gmph - lflt\r\n" + "bhrh: jmvd + tfmp\r\n" + "gdnr: msjr * tsbv\r\n" + "vqjd: zchc + vfmf\r\n"
      + "hhcq: zwzl * wgvb\r\n" + "rbbc: vvdh + nfpb\r\n" + "hspj: 2\r\n" + "zbwc: rglc * mczb\r\n" + "qvwt: 5\r\n"
      + "tvdm: 6\r\n" + "llzf: 3\r\n" + "gdpm: ldnz - tdsw\r\n" + "cscs: 2\r\n" + "vgqg: gwvb + mvsn\r\n"
      + "zwzl: hpvn + qlmf\r\n" + "vwnd: 13\r\n" + "sdlr: 10\r\n" + "cgmc: wvcc + hbrf\r\n" + "pwrc: ccgc + flht\r\n"
      + "bczt: hprb * zllz\r\n" + "fnln: fthb + cgdf\r\n" + "tjzm: 3\r\n" + "vrjv: wgrz * sczt\r\n"
      + "lrzp: wnhh + vvfc\r\n" + "wtwq: qsmt * vwnj\r\n" + "jwfd: jdds * hcpl\r\n" + "pffh: 4\r\n" + "fbzh: 2\r\n"
      + "fbdg: rlld * rwqs\r\n" + "zljm: zblv + fbrz\r\n" + "qpmb: znrs + czds\r\n" + "gvnr: qlcb * spmc\r\n"
      + "tptp: qsls + cnqf\r\n" + "ddpp: zmgv / zlld\r\n" + "cbbc: nltt * jzml\r\n" + "lnph: wfdp / gwhf\r\n"
      + "pwrh: mtpg * ldfb\r\n" + "dgwj: lgch * glvd\r\n" + "zlpp: 2\r\n" + "smwn: nntz + bqbl\r\n" + "ptcv: 7\r\n"
      + "zvbd: hbqf + dbjp\r\n" + "nbqv: 5\r\n" + "zljh: 3\r\n" + "sczt: 2\r\n" + "cnfv: jpsp * szzz\r\n"
      + "qtmc: zhcf * nbsj\r\n" + "jbdb: cngm * qtfn\r\n" + "mvjq: 7\r\n" + "jvcs: 2\r\n" + "bvvb: qqvv + wlfr\r\n"
      + "zrgb: 3\r\n" + "srdv: 5\r\n" + "dmwz: jjrv * snqf\r\n" + "pjlh: 7\r\n" + "fhzz: bblv + dzjp\r\n"
      + "nmsf: 2\r\n" + "gsft: 6\r\n" + "ngns: 10\r\n" + "mrld: 2\r\n" + "mgbb: ppnc * jjhw\r\n"
      + "rblh: mzpg + clbc\r\n" + "drcc: nphv + bzzp\r\n" + "clqt: tsmw * zhjb\r\n" + "slmv: vqrb / ljtw\r\n"
      + "rsss: pjlh * whbs\r\n" + "pjss: 2\r\n" + "mrzn: hfpg * hgvq\r\n" + "ptgt: 3\r\n" + "brdz: 10\r\n"
      + "gwsr: 16\r\n" + "flhb: 3\r\n" + "stjn: cbnt + ffng\r\n" + "njmv: bgwg * rppt\r\n" + "bswt: hvmb + lhst\r\n"
      + "frpp: htrl * vzvn\r\n" + "wtvc: fnst - glcg\r\n" + "tvzr: gbqm + vczz\r\n" + "lrmf: 2\r\n" + "cdwq: 2\r\n"
      + "tgqf: 2\r\n" + "sntj: 2\r\n" + "jmts: ncrv + rhzw\r\n" + "wsln: 13\r\n" + "dpnh: 2\r\n"
      + "gjjz: ldzd + pgjn\r\n" + "vbff: jhtv / ndww\r\n" + "ttcj: 16\r\n" + "fcls: 4\r\n" + "lsts: 3\r\n"
      + "rznm: 2\r\n" + "nrhc: 5\r\n" + "rvgw: mlgt * dfrc\r\n" + "fwnh: 2\r\n" + "ftnr: djzf + pcsb\r\n"
      + "fwwt: jbdb * gdmz\r\n" + "fvzh: svvn / gbmt\r\n" + "jcjd: vbff * ctbn\r\n" + "pmfp: lglf + qtnd\r\n"
      + "hjvq: 7\r\n" + "rwwn: 3\r\n" + "scmn: jnnz * zmgl\r\n" + "mthf: ccsp * trwz\r\n" + "pzzm: 3\r\n"
      + "jmcs: czjr + rwsb\r\n" + "npsl: rqrg * nzld\r\n" + "rhdg: 10\r\n" + "wzsb: vcfh * drcg\r\n" + "fdpf: 2\r\n"
      + "rwnd: zsnh + dvwj\r\n" + "jtwz: 2\r\n" + "hcrc: 10\r\n" + "vqbd: swqb * rgvw\r\n" + "jbdg: vpnw - fjmn\r\n"
      + "fjcv: 8\r\n" + "ngcg: 2\r\n" + "rmtc: fpmw * jjrz\r\n" + "bjgs: hfrb * zhcg\r\n" + "cbgr: ztsw + dwmr\r\n"
      + "smzt: fvzd + sqbs\r\n" + "ldzd: 4\r\n" + "lppc: sbcf * cwnj\r\n" + "nnfl: 4\r\n" + "fhpb: qdvf * rhpp\r\n"
      + "znch: lzqw - wsqs\r\n" + "tfrr: 8\r\n" + "rwpq: 2\r\n" + "ndgq: ghlr / csdp\r\n" + "rvmg: 3\r\n"
      + "jgmt: wbpw * jsfj\r\n" + "pnbv: 3\r\n" + "vvfc: tlws * cjwc\r\n" + "mdhb: cwfz + gppc\r\n" + "hmmg: 5\r\n"
      + "fslg: rvcn * cgtd\r\n" + "tdng: 2\r\n" + "sjct: pmrv * wjcj\r\n" + "qcjn: 2\r\n" + "gvsm: brrz * scdn\r\n"
      + "jlbb: 2\r\n" + "zmpn: nvrl * bdvt\r\n" + "dpqc: jbvc * rhzt\r\n" + "tqsq: nzwq * wbgv\r\n" + "zqsv: 3\r\n"
      + "chcb: 4\r\n" + "bgvl: 5\r\n" + "jfcd: htbw * mjzz\r\n" + "gbzt: 2\r\n" + "vjhq: 4\r\n" + "qtfs: 5\r\n"
      + "rvzs: 2\r\n" + "ppnb: cvtc + lcmc\r\n" + "pmdd: qqhp * njbt\r\n" + "ggpf: 5\r\n" + "tpvh: rmzs * sgqn\r\n"
      + "pmnq: 3\r\n" + "qsjt: 3\r\n" + "vhhr: svmd * lzgp\r\n" + "vvtn: 15\r\n" + "dgvm: 2\r\n" + "swgm: 6\r\n"
      + "tctl: 3\r\n" + "mtml: 3\r\n" + "qlbf: jllm + vhtb\r\n" + "fztr: 3\r\n" + "nzql: rscw / fwnw\r\n"
      + "jgth: 5\r\n" + "sznc: jrzl * qdtq\r\n" + "cqlc: 10\r\n" + "gsdt: 3\r\n" + "dbwg: 2\r\n" + "qttf: 3\r\n"
      + "zmgv: wjjj * smsw\r\n" + "gbzj: 3\r\n" + "qpvl: 14\r\n" + "gqqc: 5\r\n" + "pgnw: dbpj + qprs\r\n"
      + "hsht: clgw + vtgg\r\n" + "vlrp: 5\r\n" + "flcn: 2\r\n" + "sddm: tngw - gtsh\r\n" + "pvtp: 19\r\n"
      + "zdhq: vbcd + wwnp\r\n" + "tsmw: 3\r\n" + "vtfm: 2\r\n" + "tjmt: qsnr + vlnd\r\n" + "tgrh: sqdm + vqjz\r\n"
      + "bdww: 2\r\n" + "rsvj: jvqm + mrrb\r\n" + "ppgj: rjlc + jmts\r\n" + "qrtj: mpzr + pwrh\r\n"
      + "mbnn: sqdv * lhcb\r\n" + "cmwt: fcbp * dhjh\r\n" + "lzzz: 18\r\n" + "nnnm: jwbg / gpdp\r\n"
      + "vrtf: tmbc + qlnm\r\n" + "zjnt: 20\r\n" + "btwf: 12\r\n" + "wmdn: mgvv + vdql\r\n" + "vmdn: tmbt + pcdc\r\n"
      + "sfdz: 7\r\n" + "jrrw: dnnm / qnsr\r\n" + "bsdb: wfmp + lrlb\r\n" + "nfrf: 12\r\n" + "trrr: 5\r\n"
      + "tcwj: tjzm * fcbb\r\n" + "sgqn: tgdd + wmnt\r\n" + "vwqb: swlt - djwj\r\n" + "ghlr: zfwb * dfqm\r\n"
      + "tnvs: 1\r\n" + "bbvt: 4\r\n" + "nzzb: 2\r\n" + "nwhh: 6\r\n" + "mmtd: 3\r\n" + "ffng: cltf * zwmj\r\n"
      + "zcpl: sbjt * cznd\r\n" + "cbmf: 1\r\n" + "hbvg: jmcs + zrqm\r\n" + "qnsr: 2\r\n" + "mlwr: lzds * gswj\r\n"
      + "vhgv: fccn + gvqg\r\n" + "fgmm: 3\r\n" + "pcsb: zttd * grpg\r\n" + "tdcv: 2\r\n" + "cdzs: qqhn * vnwz\r\n"
      + "fqps: 3\r\n" + "gddv: 7\r\n" + "cjpm: 2\r\n" + "gzcm: rqnr / lmcb\r\n" + "wssl: ptnm / rjvm\r\n"
      + "ngrq: vcbf * mhww\r\n" + "dbqq: 2\r\n" + "tswc: 3\r\n" + "csjq: 3\r\n" + "jqbv: 7\r\n" + "jvrt: 2\r\n"
      + "cgsb: 3\r\n" + "wbgv: 12\r\n" + "sflw: 3\r\n" + "hrjr: 2\r\n" + "nvnz: cmwf + fmpf\r\n"
      + "rfmm: vzwv / bfjc\r\n" + "bjht: 17\r\n" + "ctvn: zdgj * sbdw\r\n" + "ndbg: qwjf * bzmg\r\n" + "rwlw: 5\r\n"
      + "vlmp: zdjr + tmbb\r\n" + "sjvl: 20\r\n" + "czlj: 4\r\n" + "mpzr: hcts + qdzq\r\n" + "rswt: 4\r\n"
      + "zvfg: 3\r\n" + "ffnh: qrgh * lqdc\r\n" + "mbht: 10\r\n" + "tcsq: dvrv + tgrh\r\n" + "dwvb: dpzb - jgqn\r\n"
      + "pwsp: 5\r\n" + "jwpc: lzvg + vhhr\r\n" + "jqhp: 14\r\n" + "plrf: 2\r\n" + "qqhn: dwbb + srjm\r\n"
      + "ljfh: rbhd + nfrf\r\n" + "nrjv: jmtz + mmdm\r\n" + "bmcm: dsps * vblf\r\n" + "hqjh: 3\r\n"
      + "fbtt: wllc + rsvz\r\n" + "wvcc: 4\r\n" + "dfqm: zjth * pdbc\r\n" + "rvhc: 16\r\n" + "bzmg: 2\r\n"
      + "zdhv: tfcl * bnbd\r\n" + "ghtc: 12\r\n" + "jdrm: pzmc + fvjh\r\n" + "pppg: 6\r\n" + "vdtp: 12\r\n"
      + "sgdt: wnnq / zhhs\r\n" + "ftdn: ztzg - zrrj\r\n" + "pqsb: vdqv * jstp\r\n" + "npdr: 3\r\n"
      + "fzvq: rftj / cpvc\r\n" + "scmr: 13\r\n" + "rfwp: pwqs * wbwb\r\n" + "vbpj: tzvw * hsbm\r\n"
      + "tswr: fhzm * mrgw\r\n" + "wllz: 4\r\n" + "pvhh: gvsm - whng\r\n" + "jnlw: 4\r\n" + "blnw: nnfl * vvjl\r\n"
      + "nfsd: 3\r\n" + "jqnz: gdzw * gfcc\r\n" + "wsqv: vqjd * mgpd\r\n" + "zjwj: thtg * qzwv\r\n"
      + "fvql: bdwg - jcpc\r\n" + "phqm: zjjw / ntcq\r\n" + "vjjj: 2\r\n" + "wbzj: 1\r\n" + "qwpj: 10\r\n"
      + "nfjw: znjh * pwzw\r\n" + "nwsq: 2\r\n" + "ssmp: rdsr - zjgj\r\n" + "pjfb: 2\r\n" + "whsb: 6\r\n"
      + "rflj: 5\r\n" + "fzgm: 18\r\n" + "bbnf: zgqj * rtld\r\n" + "bzpg: grvf * rvtp\r\n" + "jdjw: 2\r\n"
      + "mbhf: 5\r\n" + "ngrz: chnv * gmmr\r\n" + "nmfr: qvdf + wzcn\r\n" + "dstl: qqdb + nrcj\r\n"
      + "gltt: pffh * jtjt\r\n" + "tmbb: 20\r\n" + "bfng: scqc * gbfc\r\n" + "qtnd: czzn - mdpz\r\n"
      + "vjsb: cnrm + qctd\r\n" + "jwcq: csbd + bnhc\r\n" + "vtqw: 2\r\n" + "dzfg: gjjz * hzsl\r\n" + "ppvs: 5\r\n"
      + "srfg: 2\r\n" + "gqmv: 4\r\n" + "vnsc: wfsd * tgsz\r\n" + "hhlb: wfng + hbvg\r\n" + "fmcc: 10\r\n"
      + "mcqj: 16\r\n" + "zhst: 4\r\n" + "nzst: cmms + frjj\r\n" + "frsp: 4\r\n" + "djll: gnhh * nnqb\r\n"
      + "njbt: hdnw + snpt\r\n" + "nzlw: 5\r\n" + "mqcj: 2\r\n" + "rvbc: 1\r\n" + "dzwm: 4\r\n" + "stmn: 2\r\n"
      + "wddb: pjlc * gsdb\r\n" + "bpdc: 2\r\n" + "grbb: 2\r\n" + "rwgr: fjzm + ltdp\r\n" + "wrjb: hfvr * mbwm\r\n"
      + "qcpd: znnq - hmmg\r\n" + "sggg: nlpz + dctr\r\n" + "dpdw: 1\r\n" + "ptsh: 9\r\n" + "pjts: 4\r\n"
      + "clgv: dtpm * jsjh\r\n" + "tjqh: gqdh * zwwz\r\n" + "pwgh: bjbz * tvrm\r\n" + "nvrd: wnpv - spwz\r\n"
      + "cdwc: 9\r\n" + "cgtn: 3\r\n" + "vmmg: dlrj * srfg\r\n" + "sbcv: wzpr + gnsp\r\n" + "hzhb: 13\r\n"
      + "gglp: 2\r\n" + "tdnf: 7\r\n" + "nnwn: 15\r\n" + "jnmz: 12\r\n" + "clrd: frwm / llhn\r\n"
      + "rdcj: zhcm - qgsd\r\n" + "tfcv: rmdn + nbrq\r\n" + "tmfp: 8\r\n" + "rbgw: 4\r\n" + "vdqv: 3\r\n"
      + "twdd: tnth + ptnb\r\n" + "vnwz: 4\r\n" + "nfbh: 13\r\n" + "zhgb: ztjb + zhvm\r\n" + "cgdf: drrc * lrzp\r\n"
      + "dztv: dtdp * mftg\r\n" + "hnvl: 13\r\n" + "bmrb: 7\r\n" + "wftf: wpwl * fbnp\r\n" + "ngvj: 5\r\n"
      + "ndvd: 2\r\n" + "srgn: 1\r\n" + "rcfw: 2\r\n" + "glvd: whtj + sjvl\r\n" + "tzvw: 2\r\n"
      + "zsjn: jzcm * lpcl\r\n" + "cnvh: 3\r\n" + "mmrz: prsn * wsnw\r\n" + "dtmh: 2\r\n" + "rbgz: 4\r\n"
      + "jgvw: 3\r\n" + "tjfn: pnfl * djzl\r\n" + "pwqs: zndq + jwdc\r\n" + "dlfw: 4\r\n" + "vcvh: lqtt + qnlg\r\n"
      + "stdl: zfjl + hbgz\r\n" + "nwlm: jmjh + rlfj\r\n" + "wnnq: zwdd + vzmp\r\n" + "cqgw: 4\r\n" + "tbsm: 1\r\n"
      + "pdsp: cbdd + tthj\r\n" + "wqnb: dvtl / fqzw\r\n" + "cwfz: mdww + zzdp\r\n" + "fdqz: nzst * pnrq\r\n"
      + "szfm: 5\r\n" + "dqlv: 15\r\n" + "hwtm: 17\r\n" + "bnfv: shsh * mcjb\r\n" + "ffsc: vbsn + twdd\r\n"
      + "cznw: 4\r\n" + "gcvm: rdtn * crpg\r\n" + "stdg: qtvn + hvmf\r\n" + "vrqd: 5\r\n" + "qzzr: jqnz - nbqv\r\n"
      + "mjts: nmrb * wsml\r\n" + "jrgc: hrff * hspj\r\n" + "hjst: fpvv * scmr\r\n" + "chng: 2\r\n"
      + "zhlt: vlmp * jzlh\r\n" + "nbvz: njvl + mfjg\r\n" + "cnqf: rrcn * gslm\r\n" + "wdvg: 3\r\n" + "scvc: 7\r\n"
      + "tsvv: vzvb - dpwn\r\n" + "sblc: hrmp * rljs\r\n" + "bmrq: 2\r\n" + "ffdr: cltq - sqwv\r\n"
      + "fjmn: pgnv + qpzs\r\n" + "tcsr: 2\r\n" + "ngbn: 2\r\n" + "lmvs: 3\r\n" + "sfvz: dwnz + jvpm\r\n"
      + "lmzr: sfvz * gnql\r\n" + "zrzs: mdds + bvgn\r\n" + "wsmt: 4\r\n" + "vfzj: 5\r\n" + "gvqp: ljpn - zvbd\r\n"
      + "zflc: 13\r\n" + "jcww: 3\r\n" + "ntbd: 4\r\n" + "cltq: gjgm / wqcc\r\n" + "bgzm: tghl * zlnr\r\n"
      + "pngh: 3\r\n" + "hprb: twng + tpfd\r\n" + "dqzg: rbds * ctqc\r\n" + "tqsf: 4\r\n" + "rhpp: smzt * gmlp\r\n"
      + "sbrg: fbzf / mvmv\r\n" + "cphf: rwwn * fbzh\r\n" + "wttp: rmml * pscr\r\n" + "qjdc: gpvt / grhm\r\n"
      + "hsrz: vvcm + bcvp\r\n" + "lqcm: 2\r\n" + "rhgn: mpwt - tnjc\r\n" + "dbqc: njsw * jcnz\r\n" + "fplv: 5\r\n"
      + "qctd: fzvm * dpqc\r\n" + "vdbp: 2\r\n" + "bgwg: 10\r\n" + "qdsv: csjm * rrss\r\n" + "tttn: 5\r\n"
      + "hbtz: 2\r\n" + "vbcd: 4\r\n" + "nfjv: 2\r\n" + "dvzl: hfth / tgdl\r\n" + "rlhl: gqlz + ndsc\r\n"
      + "cjsg: mfmr + jfrw\r\n" + "qmtd: 18\r\n" + "qlnm: jnzm + wlqz\r\n" + "nvhl: vgjn - ptsh\r\n" + "lwrd: 3\r\n"
      + "nzrt: psjl / lffh\r\n" + "zhcf: rbgz + jcgq\r\n" + "znnq: vngd * tgmm\r\n" + "mmmb: 1\r\n"
      + "bpfd: zqrs * jbnw\r\n" + "lwdr: 15\r\n" + "hbqf: 3\r\n" + "qwhm: 2\r\n" + "ztwq: bfsb * hpvh\r\n"
      + "hdcn: 2\r\n" + "hbbg: 8\r\n" + "qqvq: htmc / dgjq\r\n" + "tgdd: chqt + gmmd\r\n" + "gnpc: tqjd + jrct\r\n"
      + "jfnb: rlhl / whjc\r\n" + "btnj: phbc + qpbj\r\n" + "mgfm: 8\r\n" + "jwlq: 5\r\n" + "bjbp: 9\r\n"
      + "jbvf: dztv + qpsd\r\n" + "pbdn: 5\r\n" + "pzrz: 9\r\n" + "qmvt: dgwj + nbfz\r\n" + "wjcv: mdhb * dhqf\r\n"
      + "jhzj: vlds - fwnh\r\n" + "vzzq: rqhq * lfrp\r\n" + "clbc: 4\r\n" + "lzrn: 2\r\n" + "zdjr: 1\r\n"
      + "llzh: 3\r\n" + "zwpb: stjn / dfzf\r\n" + "bvdp: qsjt * qmtd\r\n" + "fntd: sflw * cgqd\r\n" + "jpdh: 10\r\n"
      + "rwwp: gzmq - bgtt\r\n" + "qfrq: mtln * cgpb\r\n" + "hfrb: qfzt - gzcm\r\n" + "cfht: tswr + vpml\r\n"
      + "wfng: zshl + mpfd\r\n" + "fmqz: 2\r\n" + "zshl: 12\r\n" + "thns: 5\r\n" + "dvhd: 9\r\n"
      + "zchc: cbbb / bjbq\r\n" + "stpw: scnp * hqjh\r\n" + "zggd: cfpc * bsst\r\n" + "htrl: 13\r\n" + "vcbf: 2\r\n"
      + "gljz: vcft + hsgp\r\n" + "hszf: gjpr + wbzj\r\n" + "rlmv: 2\r\n" + "cfbs: 2\r\n" + "htzw: jmps + wftf\r\n"
      + "drrc: 2\r\n" + "rqnr: mtqj + sjcl\r\n" + "mjlr: 12\r\n" + "dvwr: vhpv + jqrb\r\n" + "dtpm: 2\r\n"
      + "jdds: 5\r\n" + "wdww: 10\r\n" + "vfhs: 2\r\n" + "zzdp: qvdn * cdlw\r\n" + "cctp: glld + dqqp\r\n"
      + "jlcz: 2\r\n" + "nqvp: lpgg * sqgn\r\n" + "dzdb: prrw * gbgm\r\n" + "rhlm: 19\r\n" + "jbnw: 2\r\n"
      + "ptnm: drbm * lqtf\r\n" + "nvmr: 7\r\n" + "tngw: cntm * plcq\r\n" + "ztjb: 10\r\n" + "wtdq: 2\r\n"
      + "nfbt: 3\r\n" + "vztr: ggrq * zhsh\r\n" + "sfzs: wfwh + mmmb\r\n" + "mltr: 5\r\n" + "lgwg: 1\r\n"
      + "ctbn: mtrg + rzhp\r\n" + "frwm: vdtp + jmrh\r\n" + "srvt: pphv + pwrc\r\n" + "hcgb: hbdf + lhbf\r\n"
      + "pzpn: ngcg * fmqf\r\n" + "cmnl: gnsq + wqfq\r\n" + "ghdf: zsld + glst\r\n" + "dhjh: zsjn + rzpn\r\n"
      + "bnbd: httj + tmnd\r\n" + "bzbj: 20\r\n" + "tnzd: 10\r\n" + "zdgj: 5\r\n" + "jqcr: ftnz * wjzt\r\n"
      + "pvsp: qqsz * tdfz\r\n" + "nbpn: 2\r\n" + "zrzq: rfmm - zfnl\r\n" + "gsfz: ccmv * cdbz\r\n" + "vwwr: 2\r\n"
      + "bptm: tmfp + hfzc\r\n" + "jqsd: 5\r\n" + "hrmp: 2\r\n" + "whlb: mmsp * whqq\r\n" + "jtjt: 2\r\n"
      + "lvhb: mgfm - bmrq\r\n" + "tmsf: 5\r\n" + "dhbj: 2\r\n" + "pqfg: zdfh * nzrt\r\n" + "rpsl: lwnl * cmlf\r\n"
      + "glzf: 13\r\n" + "rqbf: tfqt + znvv\r\n" + "mlzl: 5\r\n" + "wfsd: 2\r\n" + "bwzt: 2\r\n"
      + "htmc: nhmg * cwzm\r\n" + "nzld: 2\r\n" + "zhvm: vfsf + tgjt\r\n" + "plpb: nnvm + ljmw\r\n" + "lzpr: 3\r\n"
      + "gqlz: rshp / nwrg\r\n" + "qjgj: 8\r\n" + "qwdn: srrw + wrjb\r\n" + "twzg: 3\r\n" + "pggq: ssjp * ggtg\r\n"
      + "mbvf: dsln * zfrw\r\n" + "fjjp: zbmf * pvsh\r\n" + "hqgp: 7\r\n" + "cfpc: 2\r\n" + "ldmq: 2\r\n"
      + "drsf: pmhn * cgwq\r\n" + "hczp: hglp * mzcn\r\n" + "pjhc: psvp + bgvl\r\n" + "lptl: 3\r\n"
      + "zhcm: fzpl * bnns\r\n" + "zrrt: mzhl * mndb\r\n" + "wlts: ndtl * zvnl\r\n" + "fblr: 5\r\n"
      + "ddzt: mzqf * rznm\r\n" + "wsnw: dzdb + fhpb\r\n" + "zbtw: 3\r\n" + "ltdp: 9\r\n" + "mgbl: 3\r\n"
      + "zqsh: 3\r\n" + "nbfz: mzlc * jqbv\r\n" + "rppb: 11\r\n" + "bfjc: 4\r\n" + "lljj: 2\r\n" + "zwgm: 2\r\n"
      + "gcjz: 20\r\n" + "mfzw: fsmr * hpbd\r\n" + "bhqq: fctr * sjsh\r\n" + "gzct: dzfh * qcfb\r\n"
      + "zlrf: fvcd + jfjm\r\n" + "fnnl: 3\r\n" + "ghfj: 2\r\n" + "mdrw: rjpd + nmqp\r\n" + "lbpq: bqdp + dgjt\r\n"
      + "rzsb: cvtm + lpmt\r\n" + "wbjq: 5\r\n" + "hvmb: 2\r\n" + "lvtt: vcwr * hhzl\r\n" + "nclr: twvz + mppv\r\n"
      + "rfdr: zdjp * nbpn\r\n" + "rrmt: wdww * zvlt\r\n" + "lvsl: 2\r\n" + "pmsq: rvnf + lsls\r\n"
      + "ztzg: dzhg * dcch\r\n" + "rptz: 2\r\n" + "zhrc: sjqr * jwlq\r\n" + "rdtb: 3\r\n" + "ljgq: 3\r\n"
      + "qprs: jrmp * hzjq\r\n" + "gnsq: jgvw * zrzq\r\n" + "mvmv: 3\r\n" + "jwdc: bfml * hbbg\r\n" + "qbzl: 4\r\n"
      + "bqnr: vqpt * cncz\r\n" + "fllz: whpf * qtcw\r\n" + "rfrm: 12\r\n" + "vnqh: rplq + bmrb\r\n"
      + "pgsr: mpmv * lfpz\r\n" + "nmlc: 12\r\n" + "cnrm: snlm - vpth\r\n" + "flht: 12\r\n" + "ztdb: ljlt * nwsq\r\n"
      + "tgps: 2\r\n" + "vbbm: 2\r\n" + "czsn: vqmf * qpcj\r\n" + "bvqh: 15\r\n" + "jhjv: 2\r\n"
      + "gvnb: cmnl / flfv\r\n" + "fhzm: 2\r\n" + "wmjt: 4\r\n" + "zzgw: 3\r\n" + "dhrr: wjgn * gjhq\r\n"
      + "vfzg: drtp * vqcd\r\n" + "brpf: nmsf * zhpz\r\n" + "wrqg: gdmv * zcpl\r\n" + "qrbz: vjmv + pjrt\r\n"
      + "zlvl: nmbw + hfqq\r\n" + "hfbj: 2\r\n" + "cltf: 2\r\n" + "lgch: 3\r\n" + "swtn: csfn * vfhj\r\n"
      + "grhm: 5\r\n" + "bwdw: 3\r\n" + "qpwh: 20\r\n" + "lcqh: 5\r\n" + "tgsd: dbnv - fvvg\r\n" + "pscq: 2\r\n"
      + "rhgt: qchg * dzrf\r\n" + "vftm: 8\r\n" + "trpv: 14\r\n" + "chvd: ffhc + wssl\r\n" + "zbwr: vsrv + gmnq\r\n"
      + "dzqd: 11\r\n" + "bbgz: 18\r\n" + "ccvc: swdq * cbbh\r\n" + "wvnd: 8\r\n" + "tjqf: czpt + ghfj\r\n"
      + "gjbf: 2\r\n" + "zfvf: 2\r\n" + "dqjv: 2\r\n" + "bjwq: vtfm + psgt\r\n" + "fqbb: 16\r\n"
      + "fsff: czlq + srtn\r\n" + "mpzd: 4\r\n" + "tmbt: zjzj + jjfl\r\n" + "rsnp: 2\r\n" + "hcpl: 7\r\n"
      + "msbn: 4\r\n" + "fwjj: 6\r\n" + "hgvq: 16\r\n" + "rngf: znrl * jjpd\r\n" + "mqmv: 3\r\n" + "njbw: 2\r\n"
      + "zrlq: nbwv + ttcj\r\n" + "gcbq: ncsq * plqh\r\n" + "qvmh: rszz * tdcv\r\n" + "zwwz: 10\r\n"
      + "lnnt: tbfg + lvtr\r\n" + "vjgw: bwwj + mgms\r\n" + "pnnv: 4\r\n" + "fctr: fgpd + wtvc\r\n"
      + "pdbc: qpmb - pwsd\r\n" + "gqrt: jpgm + tfcv\r\n" + "rlct: jgwv + szmg\r\n" + "dfqj: hnvl * fwgq\r\n"
      + "dzfh: 2\r\n" + "vdrb: ddth * gzmd\r\n" + "zrrj: thbs / rtpg\r\n" + "qdtj: dncm + fbdg\r\n" + "zqcw: 2\r\n"
      + "msjb: 17\r\n" + "zwmj: qwfl - wtpr\r\n" + "nmlf: 13\r\n" + "bdwq: vwcj * fdzh\r\n" + "qzwv: cdwm + pdms\r\n"
      + "bcrh: wbcq * wqwc\r\n" + "cplw: dpdw + pltc\r\n" + "hhlg: qjdc + zphb\r\n" + "fvzd: 5\r\n" + "bdvt: 5\r\n"
      + "nqqc: 11\r\n" + "gjfq: 4\r\n" + "dfpp: 11\r\n" + "zdpd: 5\r\n" + "jdtz: 15\r\n" + "npmn: rcrc + qhbj\r\n"
      + "hmqf: zlpp * sqvc\r\n" + "jvqm: 4\r\n" + "drvn: wrqg / dggn\r\n" + "ztsw: 2\r\n" + "tgmm: mqmp + zqsv\r\n"
      + "lmcb: qlvz - jntq\r\n" + "dwbb: wsmt + gsww\r\n" + "hmcr: wmdn - lbgt\r\n" + "lcql: 2\r\n" + "pjhf: 4\r\n"
      + "fjdh: jspg + pqvp\r\n" + "vzvn: wtmn + ffdr\r\n" + "mlzh: qpzm + pqcf\r\n" + "shzb: 2\r\n" + "dnnz: 3\r\n"
      + "fthn: 6\r\n" + "pnrq: cndq - qhtf\r\n" + "vzzv: 5\r\n" + "rwsb: 7\r\n" + "hzvr: 7\r\n"
      + "glph: bfwb * bsct\r\n" + "qtqb: 2\r\n" + "bzzr: jcvf * ptgt\r\n" + "jdpr: 7\r\n" + "rdsr: qfpw + qlfm\r\n"
      + "bsmq: nstg + nfjn\r\n" + "lwcl: 5\r\n" + "hzpt: tjqn * zwgm\r\n" + "sfbr: 4\r\n" + "lphd: 7\r\n"
      + "vgtd: rhwl + plrm\r\n" + "gtgs: 3\r\n" + "ndsc: qnms * ghdf\r\n" + "jrmp: wnhl * vtbn\r\n"
      + "lrlb: djlt * tzrh\r\n" + "hlbw: 2\r\n" + "ntgb: 4\r\n" + "tzrh: 2\r\n" + "ctwv: 2\r\n"
      + "vsjl: rvwf * hfgm\r\n" + "vwdq: 5\r\n" + "cpvc: 5\r\n" + "hrvm: lrrc + rhgt\r\n" + "mjms: tjpf * rbgw\r\n"
      + "phbc: swtn + fbvw\r\n" + "mbff: 17\r\n" + "plnt: bdwq / vzlj\r\n" + "qngc: cgzj + cbgr\r\n"
      + "qctr: qszd * bwdw\r\n" + "fcbb: hbfc * hszf\r\n" + "wzbz: lvll - rbbc\r\n" + "jntq: 2\r\n"
      + "hrgw: rvgw / nmfr\r\n" + "gnql: 2\r\n" + "cgpf: lphd * msbn\r\n" + "qszj: btdv + hgmg\r\n" + "grvz: 14\r\n"
      + "frdv: mntv * csjq\r\n" + "qprb: tsrq * fmqz\r\n" + "wlfr: 19\r\n" + "hfpg: tcdf + qtdv\r\n"
      + "fdft: cpvv * mvnq\r\n" + "nrcs: jbpp + rlnm\r\n" + "nzwq: 2\r\n" + "bvgn: rphc + brhc\r\n" + "jjmv: 3\r\n"
      + "zjnr: 4\r\n" + "mflt: jplp - wbwv\r\n" + "czsp: nrcs - cvws\r\n" + "mpdz: 2\r\n" + "djmj: hjvp + zzlt\r\n"
      + "rmqp: 4\r\n" + "fpwf: qngc + lwdr\r\n" + "zvqs: 7\r\n" + "pczc: 4\r\n" + "vpml: 11\r\n" + "vpth: 14\r\n"
      + "jmjh: 1\r\n" + "lhwr: 2\r\n" + "qwlg: npnl + cjcs\r\n" + "mcpd: 15\r\n" + "ppnc: zrdn * vgqn\r\n"
      + "zrhn: qgzc + qhnn\r\n" + "bqlq: 3\r\n" + "jpcd: rngf * grrg\r\n" + "qdpg: qfgd + wqsh\r\n"
      + "vgjb: pqzr * wtlh\r\n" + "pbbs: lmnb * csbn\r\n" + "mjhf: cjbs * fwfm\r\n" + "dnnm: gbjj * vtqw\r\n"
      + "vgfg: 9\r\n" + "lcwh: zjwj - fgmm\r\n" + "jvrs: ggmm * qdft\r\n" + "nsjs: pmfp + nlnq\r\n"
      + "lpmt: zggd - bsbj\r\n" + "qnlq: slmv - vhhz\r\n" + "znlj: zzqr + zlvl\r\n" + "jmtz: 1\r\n" + "mhnm: 4\r\n"
      + "wbwb: glcj * tbqn\r\n" + "jjqm: 3\r\n" + "qdvf: mcqj * shpb\r\n" + "jgrz: ssjl * rvzs\r\n"
      + "hrhd: fbqh * zbfq\r\n" + "pwpv: 5\r\n" + "hvdw: 16\r\n" + "mdpw: 3\r\n" + "nbgn: 8\r\n"
      + "gswj: cgld / gsft\r\n" + "phwn: 4\r\n" + "sbjt: 2\r\n" + "djqt: nnzl - spwb\r\n" + "zmgl: 3\r\n"
      + "zjlf: nbgv / hpts\r\n" + "tbvv: 3\r\n" + "mdsv: 8\r\n" + "dvrv: 4\r\n" + "cmqw: 19\r\n"
      + "nbgv: dqsb + jltr\r\n" + "smfr: 2\r\n" + "sgfn: 4\r\n" + "qdbn: ftdn + smwn\r\n" + "njrj: 3\r\n"
      + "dmff: pqfg + gtpq\r\n" + "jtrr: zwpb - pmtb\r\n" + "njvh: 12\r\n" + "brjd: 2\r\n" + "ddsz: mrzf + mcnc\r\n"
      + "wfqv: 14\r\n" + "czdr: 4\r\n" + "pcwh: 5\r\n" + "tjfp: jchb + ffsc\r\n" + "blcp: 15\r\n"
      + "hbtm: mnsg * jdjw\r\n" + "pcrg: 4\r\n" + "jgqn: dzwm * hbzt\r\n" + "hzsl: 3\r\n" + "whpf: 3\r\n"
      + "gsww: spfn + rwjb\r\n" + "pjjj: 2\r\n" + "mdww: dtpj * jbdg\r\n" + "rftj: mdmc * dwvb\r\n"
      + "mdmc: czlj * nclh\r\n" + "sffw: 2\r\n" + "vdjc: vcwq * qnjp\r\n" + "zbpb: nsjq * lcqr\r\n" + "wqrc: 6\r\n"
      + "rlld: 3\r\n" + "gdnh: qbnc + vcqz\r\n" + "qznw: rlbw * mnrg\r\n" + "clhh: 4\r\n" + "bvwq: pllj * szfm\r\n"
      + "hdth: 11\r\n" + "cprw: 4\r\n" + "jspv: 2\r\n" + "blrj: 3\r\n" + "fhdq: hjtt + zhfr\r\n"
      + "fzwl: bmws + hlgg\r\n" + "rwwt: llsj * zbqr\r\n" + "gbfc: 8\r\n" + "fbbw: ddhr * nvnz\r\n"
      + "dwcr: ncbr + wvlm\r\n" + "vgqn: rvbc + sqjj\r\n" + "jqmb: bdvc * bhgf\r\n" + "njsw: flcn * jgrz\r\n"
      + "rjjp: 3\r\n" + "qrng: 4\r\n" + "nsfl: 6\r\n" + "vfmf: vvps / sfrz\r\n" + "qzvc: nsfl + frgv\r\n"
      + "lznv: gpsq - fbhf\r\n" + "wnzn: 3\r\n" + "lfrp: 2\r\n" + "ldfd: 2\r\n" + "mzwd: 4\r\n"
      + "qtvn: bmcm / rcfw\r\n" + "vcfh: hjsb + sbfs\r\n" + "dbnv: dbzf + cllt\r\n" + "gvmh: 5\r\n"
      + "hrff: qbdv * hfwt\r\n" + "ggzn: sfqg * mlzl\r\n" + "jmvd: zghf * bqpz\r\n" + "qzdw: 5\r\n" + "pgjn: 3\r\n"
      + "dqqp: fdpc * zljh\r\n" + "jphj: 3\r\n" + "fccn: jfcd + mwbn\r\n" + "gnzm: jcjm * lcpg\r\n" + "mgwr: 2\r\n"
      + "vqpt: 3\r\n" + "sgjw: 5\r\n" + "wjgn: drqf - tnvs\r\n" + "ftqd: 4\r\n" + "mflp: jjmv * prcp\r\n"
      + "qwts: 2\r\n" + "mmcj: pwwf / vqzz\r\n" + "pftr: dhsj + mbvf\r\n" + "zllz: 3\r\n" + "hfvz: 3\r\n"
      + "ptlp: 11\r\n" + "dwnz: pcvg * zdpd\r\n" + "bggf: shwm * wzsr\r\n" + "tmbc: ftjz + rpwm\r\n"
      + "hbdf: zqtv * tpnp\r\n" + "qzqh: zzlh * gqrt\r\n" + "cvff: jdpr - cvrn\r\n" + "wsqs: ljmb + nclr\r\n"
      + "dnhv: 2\r\n" + "bjbz: 3\r\n" + "pgff: 3\r\n" + "vfpw: bgng * lgdc\r\n" + "sbpg: 1\r\n" + "ssvw: 11\r\n"
      + "vwhc: 3\r\n" + "hsmc: mqcj * nwfb\r\n" + "qsjv: npvp * gsfn\r\n" + "pznh: 4\r\n" + "vhsv: stps * svzn\r\n"
      + "frlr: 2\r\n" + "bzrd: 20\r\n" + "bpcr: 2\r\n" + "vhpv: 1\r\n" + "tghl: 2\r\n" + "lhpq: 7\r\n" + "jjpd: 5\r\n"
      + "rppt: 4\r\n" + "scph: 5\r\n" + "mgjg: 3\r\n" + "fvjn: 6\r\n" + "hddc: gvhh * wvrt\r\n" + "vhmb: 6\r\n"
      + "plqh: gsdt * chtl\r\n" + "zlzm: trrr * gpdh\r\n" + "pjlp: zqsh * glnf\r\n" + "hsbm: 11\r\n"
      + "rzpn: vvpf + jqhp\r\n" + "tncf: 16\r\n" + "lfvc: 1\r\n" + "gpvt: vhsh + drjj\r\n" + "gnvc: qpgn + hsrz\r\n"
      + "vbwv: rptz * pvhh\r\n" + "pjlc: 3\r\n" + "vmhz: 3\r\n" + "vcpt: rzjr * lrmf\r\n" + "nmrb: vdbp * ctmd\r\n"
      + "njvl: bwfr + lzcm\r\n" + "drjj: pfhr * sltc\r\n" + "djzl: 2\r\n" + "htmr: 8\r\n" + "ncrv: 11\r\n"
      + "vqrb: jqzb + gphr\r\n" + "bgtt: 3\r\n" + "whsh: 15\r\n" + "sgnv: 4\r\n" + "wqnn: znfr / vrjw\r\n"
      + "wzsr: 2\r\n" + "jfgl: scph * mbtd\r\n" + "mfmz: gnzh + ztsv\r\n" + "zqms: 1\r\n" + "frbm: 4\r\n"
      + "qchc: 1\r\n" + "lgvb: hbtm * gvwq\r\n" + "pmzn: hssd + gqqs\r\n" + "rscw: zdhv - nnnm\r\n"
      + "csjh: cfth * svzw\r\n" + "rplq: hgfq * chcb\r\n" + "fbzf: ltzr * htvr\r\n" + "nnzl: mfqh * njbw\r\n"
      + "bdqv: 2\r\n" + "zwbh: 2\r\n" + "qlfm: hpgr * pnpj\r\n" + "wvvc: jjgl + csgn\r\n" + "tflc: 4\r\n"
      + "ttlz: sssd + tpdq\r\n" + "czlq: 8\r\n" + "lzvg: 19\r\n" + "qpts: mgwr * ngjw\r\n" + "gmnq: jnmz * rvcj\r\n"
      + "qgrd: 5\r\n" + "hbfb: 3\r\n" + "mrzf: cctp / qmrn\r\n" + "hsdq: lgqg + bdgp\r\n" + "fbqh: 13\r\n"
      + "gqdh: 3\r\n" + "rpwm: rfgn + qpts\r\n" + "crqc: ssvw + npsl\r\n" + "fprn: 2\r\n" + "lcpg: 2\r\n"
      + "gtds: tllq / thgt\r\n" + "ljlt: 5\r\n" + "gmqq: nsfj * sdmj\r\n" + "vgdl: qlbf + zhgb\r\n" + "pcvg: 2\r\n"
      + "zrdv: 3\r\n" + "gdrg: 2\r\n" + "rqqn: cdbm + vvzw\r\n" + "dvwj: rbgt * nhmn\r\n" + "dvbj: fcdg * nszj\r\n"
      + "bwfr: sbwp * qfsf\r\n" + "gbpf: 2\r\n" + "pfvw: fbpt + lvsl\r\n" + "qnhl: 2\r\n" + "mtrg: 11\r\n"
      + "shnf: fqbb * scnq\r\n" + "rmdn: bsdb - tvzr\r\n" + "fdcm: djtb + sscl\r\n" + "llhh: 3\r\n"
      + "mfbs: qcpd + vmmg\r\n" + "tbbb: pwtl * clgn\r\n" + "gjvv: jfqh + fmjp\r\n" + "vghs: 2\r\n" + "gzpd: 19\r\n"
      + "wbql: tzws + tptp\r\n" + "fbhf: 1\r\n" + "svpq: 2\r\n" + "jhrq: pbbs + hzpt\r\n" + "czjr: 4\r\n"
      + "sstl: 8\r\n" + "clsg: msjb * dvzl\r\n" + "jrct: 18\r\n" + "lggn: pvtz + jljf\r\n" + "swqb: tmfz / zjnr\r\n"
      + "mvtd: 2\r\n" + "qpzs: psbm * wrcz\r\n" + "rvrm: 5\r\n" + "pctr: 5\r\n" + "wlqz: 14\r\n" + "dmfh: 5\r\n"
      + "jpsp: 2\r\n" + "hzbt: 4\r\n" + "rfgn: wzmw * wvfg\r\n" + "jstp: 3\r\n" + "srjm: 12\r\n" + "cvrn: 1\r\n"
      + "cllm: bfpf - tpvh\r\n" + "smsw: mvlm + vhqf\r\n" + "jbjs: 19\r\n" + "gzbb: 3\r\n" + "cwlr: cvwg * thws\r\n"
      + "lphc: tfnn * qbjj\r\n" + "zhpz: 3\r\n" + "njqn: 2\r\n" + "hbrf: vpsd * ltwz\r\n" + "jwbg: qdhf * dfmv\r\n"
      + "bcvp: 7\r\n" + "tqcl: qfrq + qgvw\r\n" + "mflm: 3\r\n" + "gvhh: ngrz - zvrf\r\n" + "nsfj: 2\r\n"
      + "wzcn: 5\r\n" + "czzn: pfsw + bnbp\r\n" + "fdrw: 2\r\n" + "hmjc: glrv * hzbt\r\n" + "ctqc: 3\r\n"
      + "vhzh: tvgh * lnph\r\n" + "cnfb: 5\r\n" + "hlgg: 2\r\n" + "fwfm: ttbd * njqn\r\n" + "clpm: smjq * hqzq\r\n"
      + "bdvc: 2\r\n" + "cdbz: 2\r\n" + "mcjb: 3\r\n" + "psrc: 9\r\n" + "gtdv: fmll * qzdw\r\n" + "dsln: 5\r\n"
      + "mlpm: 6\r\n" + "fwjs: 3\r\n" + "ghrq: 2\r\n" + "zrwp: hmqf + dgnr\r\n" + "dqsb: wvpt + vgjb\r\n"
      + "gzwt: 2\r\n" + "tgjt: pqsb + jvwm\r\n" + "wwcj: gqtp + jhqv\r\n" + "vcvv: ddzt + fgsj\r\n"
      + "mzhs: qddv * plmm\r\n" + "mpqp: qdsb + ccvc\r\n" + "hjvp: djqt + qvfg\r\n" + "dqcv: 2\r\n" + "cvrf: 5\r\n"
      + "tbfg: 4\r\n" + "vbmc: pmdd + bgtv\r\n" + "hhzl: 2\r\n" + "rlnm: mnsl + hllf\r\n" + "zcwd: 14\r\n"
      + "grrb: vjhn + nfll\r\n" + "tvgh: 4\r\n" + "wbjf: hvmj + rvmj\r\n" + "rzhp: 2\r\n" + "tqfm: 10\r\n"
      + "qdhf: lgvb - ttgq\r\n" + "gjgm: mjrn * plnt\r\n" + "hnlq: 5\r\n" + "vdhp: 13\r\n" + "vgnb: 2\r\n"
      + "fpsl: btnj + bmcp\r\n" + "qbdv: 19\r\n" + "cbvr: mjjr + sdsz\r\n" + "hgnb: 9\r\n" + "tdbw: llzf * fbdp\r\n"
      + "zrqm: 19\r\n" + "pnvw: 3\r\n" + "vvdh: gdcb * dstl\r\n" + "fqrw: jhrq * vfrb\r\n" + "frcr: 5\r\n"
      + "hprq: 3\r\n" + "csdp: 2\r\n" + "dtpj: 2\r\n" + "rdtm: djrf * lphc\r\n" + "tdsw: 11\r\n" + "qqhp: 3\r\n"
      + "cwpq: 3\r\n" + "mgqp: 17\r\n" + "dmzl: 2\r\n" + "tpdq: hdlf + mnwn\r\n" + "wbwj: 4\r\n"
      + "mtwr: tnhv - grmd\r\n" + "rlbw: dpwf + nzql\r\n" + "dmzh: 5\r\n" + "fsmr: 2\r\n" + "wwqp: 10\r\n"
      + "jcnz: rjbv + fjcv\r\n" + "csbn: 3\r\n" + "hjtt: ffnh * mjzq\r\n" + "vqrf: 4\r\n" + "fcdw: hcfb + nbmf\r\n"
      + "qtdv: qdtr + smrt\r\n" + "tlmt: lcmp * npdr\r\n" + "hpts: 4\r\n" + "lsvq: mrbc * wnvp\r\n" + "dwhw: 5\r\n"
      + "nbrq: 2\r\n" + "zsgr: 17\r\n" + "cqvw: jpdh + jwtt\r\n" + "zwvp: ctvn * gwhn\r\n" + "mnwn: 4\r\n"
      + "dctr: wvvc * mzth\r\n" + "ljpn: jsdq * vctc\r\n" + "bjbf: cjsg / zgss\r\n" + "cmms: 3\r\n"
      + "mzcn: jgth * nsbc\r\n" + "bwvs: gcvm + hmtj\r\n" + "szzz: zddg - nmvc\r\n" + "flrl: wdsz * sqdb\r\n"
      + "jntw: 2\r\n" + "qmfw: 2\r\n" + "rlfj: 16\r\n" + "wznp: fqnw * gtqf\r\n" + "sjqr: 5\r\n"
      + "frwq: gdnr + fjjp\r\n" + "smwd: 2\r\n" + "vblj: tqqs - qbzl\r\n" + "fhct: mbht - zlth\r\n" + "wvrt: 2\r\n"
      + "tgmr: 2\r\n" + "qcqt: clqt + fwsm\r\n" + "bsgh: 2\r\n" + "vvmq: clpm * msrv\r\n" + "zwgv: 3\r\n"
      + "ssmh: 2\r\n" + "stdh: mlpw * htpc\r\n" + "hzjq: 3\r\n" + "rdtn: sfpn * rbjz\r\n" + "hchh: zvpt * cprw\r\n"
      + "cqvz: 3\r\n" + "vrjq: zfrt * vdjc\r\n" + "ddfl: 1\r\n" + "qqdb: 13\r\n" + "cgtd: dhrr + pjgm\r\n"
      + "nghl: gzgt + srfc\r\n" + "dqlg: 2\r\n" + "gvrg: crnh * cgtn\r\n" + "cncz: 11\r\n" + "wmjb: rwnd + ntqg\r\n"
      + "bwft: mhnm * plrf\r\n" + "zfqr: wdcf + mltr\r\n" + "pnpj: 2\r\n" + "fdzs: 5\r\n" + "ctjt: dvbj + cfqc\r\n"
      + "rzjr: 4\r\n" + "pqhl: fpzt * cdzm\r\n" + "slfr: 2\r\n" + "zmlz: 2\r\n" + "zjth: 2\r\n" + "tjpf: 3\r\n"
      + "rmzs: ghsn + lrmj\r\n" + "ftgt: vvmq + czsp\r\n" + "fdpl: 2\r\n" + "vvzw: nmlf + cbnb\r\n"
      + "nztf: pdsp + pljh\r\n" + "bsst: nwhh + gfwm\r\n" + "jwtt: 3\r\n" + "lqpg: blsp + sbrq\r\n"
      + "dwmr: bqnr + vdrb\r\n" + "gsdb: 3\r\n" + "rvbs: 3\r\n" + "wzpr: fpcj * vlhd\r\n" + "rmbs: 3\r\n"
      + "ndtl: pqpc + vgdl\r\n" + "dzfj: 2\r\n" + "wgvb: 3\r\n" + "spfn: 2\r\n" + "jnnz: nbsg - drjb\r\n"
      + "lglf: fnnl + bjbp\r\n" + "thbs: vshl + ndgq\r\n" + "jmrh: zbwc * jhsp\r\n" + "lfhj: 5\r\n"
      + "pjrt: ncrs + bwrv\r\n" + "qfzv: 3\r\n" + "fsnw: 4\r\n" + "thlb: vztr + qvhm\r\n" + "gnbg: 2\r\n"
      + "wmzm: 4\r\n" + "mczb: 4\r\n" + "svcl: 4\r\n" + "rbvg: hcrc + fdft\r\n" + "zwdd: vjgw + pcdj\r\n"
      + "scnq: 3\r\n" + "nfll: qtvf + mthf\r\n" + "pmdj: 3\r\n" + "rtcs: wgjr * lvhb\r\n" + "qznc: 11\r\n"
      + "shsh: ghhs / vjjj\r\n" + "ndww: 2\r\n" + "wbcq: 4\r\n" + "fjwd: 6\r\n" + "lhbf: smml * vnsc\r\n"
      + "wvsq: wrrj + qgrd\r\n" + "vblf: 2\r\n" + "njnh: hpjh * dszw\r\n" + "wmjr: 1\r\n" + "gsfn: 15\r\n"
      + "rzcn: dvmm + pzcl\r\n" + "gphl: mmrz + bjrg\r\n" + "dbjp: 4\r\n" + "zfjl: wfjv * rfhc\r\n"
      + "vwzw: jzjg + mptj\r\n" + "sbdw: hrnj + zlzm\r\n" + "vslw: 1\r\n" + "gjjq: nsjs / tvff\r\n"
      + "pgcv: qdpg + vnqh\r\n" + "lvll: vzpq * grmn\r\n" + "cdlw: 3\r\n" + "qjqf: ntbd * rfdr\r\n" + "gpdp: 3\r\n"
      + "jmlm: 9\r\n" + "mwrm: dzfj * wsln\r\n" + "bjwr: dhcw * zzgw\r\n" + "mzlc: lbpq * dssw\r\n"
      + "cbjw: jhmn + plwg\r\n" + "svzn: bdtw * rdtb\r\n" + "hmsn: 2\r\n" + "tczj: 5\r\n" + "vsfn: 3\r\n"
      + "vfhj: 2\r\n" + "zddg: qzzc * hwrd\r\n" + "mhww: nrjv - bfhc\r\n" + "rljs: 5\r\n" + "hdrs: 15\r\n"
      + "znfr: hcgb * tqsq\r\n" + "ggsg: 2\r\n" + "dlhr: 2\r\n" + "qdtw: mhcv * nrpc\r\n" + "rtbd: grvz + dpct\r\n"
      + "dtdp: 9\r\n" + "jsdq: 3\r\n" + "vwcj: gmjh + qrbz\r\n" + "zrlw: 19\r\n" + "cqpw: fwwt * htgs\r\n"
      + "fnst: qzzr + shnf\r\n" + "tcwn: 2\r\n" + "gwcr: 2\r\n" + "pcdj: 1\r\n" + "blwl: wddb + nzzb\r\n"
      + "gcwq: fbbw + hrgw\r\n" + "btqq: zjlf - nvfz\r\n" + "srtq: gsbq * vhsv\r\n" + "hlmd: tjrz * dwhw\r\n"
      + "lzgp: 2\r\n" + "wglm: hrvm + njmv\r\n" + "qfdw: vhmb + vszb\r\n" + "gchj: mctt + tcwj\r\n"
      + "gjhq: tgps + bpqt\r\n" + "gtqf: ssrj + tbbb\r\n" + "dvmm: twgq * rmtl\r\n" + "qztm: 16\r\n"
      + "gqnt: qjgz * pjmd\r\n" + "fbrz: 1\r\n" + "rqrg: rlmv + vrqd\r\n" + "wjrn: 2\r\n" + "tmjs: 2\r\n"
      + "jwms: fllz + jbdz\r\n" + "hjfv: 4\r\n" + "jchb: ssbg * gwwq\r\n" + "hhcg: 4\r\n" + "tpnp: vlnn + gnzm\r\n"
      + "brsg: bnfv + gqnt\r\n" + "vfws: shtp - bzrd\r\n" + "jnll: 11\r\n" + "bhgf: 13\r\n" + "dhsj: hhbw + qdrh\r\n"
      + "fsmc: 5\r\n" + "rmhh: 2\r\n" + "cllt: qbjc + cmth\r\n" + "fwfl: vzsj * zjnt\r\n" + "fvfr: qrtj / gdrg\r\n"
      + "psbm: 3\r\n" + "lwnl: bfsf * vftj\r\n" + "gcnf: ptmq + tzjq\r\n" + "qscr: gnvc * mrqq\r\n"
      + "srwm: vhrm + hdzg\r\n" + "hbtq: 3\r\n" + "dggn: 4\r\n" + "wlpw: 3\r\n" + "phwt: bzzr + hhlb\r\n"
      + "tptl: stdh + hhpr\r\n" + "jbws: 2\r\n" + "mwbn: cggh - ttgj\r\n" + "gppc: ctjt * jwpq\r\n"
      + "qlhp: hnpr + ngvj\r\n" + "ghsn: fjwd * bztc\r\n" + "vlds: bbgz + qcqf\r\n" + "psgt: qpcp + nbgn\r\n"
      + "hzjz: 10\r\n" + "sjjs: rvbs + bcqw\r\n" + "nwfb: 3\r\n" + "qdtr: rblh * qvjz\r\n" + "clgn: 3\r\n"
      + "rmml: 19\r\n" + "lgns: bqmq + pfzj\r\n" + "qwjb: wldh * szqj\r\n" + "crfl: 7\r\n" + "qtcw: 2\r\n"
      + "nvcm: 3\r\n" + "bdtw: fcdw + wznp\r\n" + "qfpw: vwnd + mpzd\r\n" + "nvpv: fjdh * jphj\r\n" + "vgrf: 2\r\n"
      + "pcqj: jrpg * hzjz\r\n" + "vjfl: lsts * wrtj\r\n" + "fmpf: gmhq - tnph\r\n" + "wrtj: 3\r\n" + "bztc: 5\r\n"
      + "tqjd: 1\r\n" + "mspg: 8\r\n" + "ctbq: fdcm / dlhr\r\n" + "jprv: 7\r\n" + "jcjm: ggpf * frcr\r\n"
      + "rglc: 2\r\n" + "cstd: qwts * wbwj\r\n" + "wqgv: 2\r\n" + "lzjw: 4\r\n" + "jjhw: hvlq * nmwz\r\n"
      + "phmw: gzbb + brdz\r\n" + "rsvz: ssmh * zflc\r\n" + "jbpp: mlwr * ppcv\r\n" + "lrmj: gcnf * gzwt\r\n"
      + "wnhh: 5\r\n" + "qzzc: jttb + brsg\r\n" + "jsmt: 3\r\n" + "lcmp: ntgb + bvlp\r\n" + "httj: tsmp * rwlw\r\n"
      + "bnbp: hdcn * glzm\r\n" + "thgt: 4\r\n" + "dnvl: wgnd * qcqt\r\n" + "zzqr: rszb * qvmh\r\n" + "njcp: 3\r\n"
      + "lvtr: nzlw * tfgt\r\n" + "nhmg: wmjt * rvmg\r\n" + "gcdv: 5\r\n" + "wdsz: wzbz + bhrh\r\n"
      + "dsps: fsts + vwfs\r\n" + "hppm: 7\r\n" + "wjjj: 2\r\n" + "ptjd: jmlm + pmfg\r\n" + "bvlp: 3\r\n"
      + "tfjp: lwcl * dlfw\r\n" + "prsn: 2\r\n" + "tvrm: fsff + frlr\r\n" + "grpg: 3\r\n" + "jvwm: 2\r\n"
      + "ltlq: vlrw - gbzt\r\n" + "qnms: 2\r\n" + "mfqh: 7\r\n" + "ccmv: zrlq + lctt\r\n" + "bpqt: 4\r\n"
      + "zbmf: tlpf + gtdv\r\n" + "tfgt: 5\r\n" + "lpnt: 3\r\n" + "ghhs: jnll + hlmd\r\n" + "gmlp: 2\r\n"
      + "mwfm: bptm * zrdv\r\n" + "pmtb: pbpb * sbpf\r\n" + "rjpd: lchn + fvql\r\n" + "scth: jvrs * mmcc\r\n"
      + "scnp: 7\r\n" + "prrl: 2\r\n" + "rdws: mgws + zwrl\r\n" + "gbwh: fslg + jhbw\r\n" + "zhsh: 2\r\n"
      + "pshv: rwwt + vshb\r\n" + "brnp: rrsz + gqqc\r\n" + "htpc: 2\r\n" + "zlth: 3\r\n" + "hhpq: 2\r\n"
      + "rnlp: 3\r\n" + "csbv: 6\r\n" + "gqtp: 8\r\n" + "mpmv: jhqz / cfpj\r\n" + "zcmj: 5\r\n"
      + "brhc: rfwp - vzzq\r\n" + "gpdh: vnvm + pzpn\r\n" + "lhlc: jwcq * bzrm\r\n" + "zvbr: 2\r\n" + "hfgm: 9\r\n"
      + "zndq: 11\r\n" + "cffl: chng * clhh\r\n" + "zbfz: 14\r\n" + "npvp: nfsd + cphf\r\n" + "rbjz: lptf + sqlv\r\n"
      + "wjcj: bvdp / vrfw\r\n" + "blwg: 2\r\n" + "hnlg: 3\r\n" + "jqjz: 2\r\n" + "wplz: swgm * ttrr\r\n"
      + "pltl: vftm + mfbs\r\n" + "gjjr: jtqg * ggzz\r\n" + "thcd: 2\r\n" + "mctt: gdmw * pnnv\r\n"
      + "hvmj: ncsd + ndbg\r\n" + "lcqr: rbvg * tblv\r\n" + "gjhp: 2\r\n" + "tnph: rpql * rsvj\r\n" + "qctj: 2\r\n"
      + "tbgq: fbvn * grrb\r\n" + "vpnw: sljt * sdlr\r\n" + "shrn: bbtw * tfzh\r\n" + "zqtv: qztm + sjct\r\n"
      + "sgqw: swrr + gmqq\r\n" + "tsbv: tdgv * gljz\r\n" + "ljgl: vfft * rzsb\r\n" + "hdzg: 5\r\n"
      + "dhcw: rvhd + jngh\r\n" + "tlqc: 2\r\n" + "fgwt: 1\r\n" + "hpvn: 15\r\n" + "gbmt: 4\r\n" + "vvcm: 6\r\n"
      + "cznd: jhzj + cfht\r\n" + "rhvb: stcq * dqzg\r\n" + "gmtm: 2\r\n" + "tvlf: 5\r\n" + "zrzv: 2\r\n"
      + "npnm: trtj + fdpl\r\n" + "jngh: 8\r\n" + "wmnt: ndqh * lzpr\r\n" + "hqzq: 4\r\n" + "pdms: 2\r\n"
      + "bwjw: cmrl * bqlq\r\n" + "pqpc: bzjl * dgwd\r\n" + "zdhl: fdqz + wbjf\r\n" + "fffr: 3\r\n"
      + "nnqq: tsvv + pbdn\r\n" + "mrgw: 15\r\n" + "jjqv: 8\r\n" + "fmll: hnlg * wdvg\r\n" + "ftnz: 12\r\n"
      + "lcmc: tppw * jpgp\r\n" + "wfjv: 19\r\n" + "rbsz: 5\r\n" + "hblg: qchc + lfgf\r\n" + "gslz: fwnb * gbhr\r\n"
      + "lmhg: 3\r\n" + "rvzf: 3\r\n" + "rqhw: zrrt + wssm\r\n" + "mrbc: 3\r\n" + "lpgg: 2\r\n" + "rszb: 8\r\n"
      + "gdmv: 2\r\n" + "bpvv: 2\r\n" + "fpvv: 3\r\n" + "jjrz: stpw + bssl\r\n" + "prcp: 5\r\n"
      + "ttbd: mqgn * wtsl\r\n" + "dlcm: 7\r\n" + "pfgq: 5\r\n" + "dfrc: 7\r\n" + "wtmn: fnwt * sggf\r\n"
      + "fbcn: pzsc * glzf\r\n" + "vrjw: 8\r\n" + "zndn: 8\r\n" + "wvpt: mdwr * pznp\r\n" + "crtb: pctr * grmz\r\n"
      + "lntg: 2\r\n" + "vngd: 2\r\n" + "zghf: 5\r\n" + "rfhc: 3\r\n" + "gvqg: mjhf / jhjv\r\n"
      + "zhfr: lznv - mthd\r\n" + "lvch: 4\r\n" + "dmsh: mvtd * vsjl\r\n" + "fvgq: fjcs * ddpp\r\n" + "ldtg: 5\r\n"
      + "fwsm: pftr + qwtc\r\n" + "mrcb: 3\r\n" + "twng: 4\r\n" + "nptf: 3\r\n" + "mtrw: 13\r\n" + "tblv: 3\r\n"
      + "zzlh: zmdj + wmjr\r\n" + "jsfj: 3\r\n" + "mmsp: 2\r\n" + "ssbg: 7\r\n" + "rndw: pmhg * dqlg\r\n"
      + "drtb: 15\r\n" + "tjtt: vbmc * bhwb\r\n" + "djrv: lmld + rglf\r\n" + "mzhl: 4\r\n" + "glld: 1\r\n"
      + "nsjq: 4\r\n" + "vszs: rndw * qnzm\r\n" + "bqmq: 2\r\n" + "rtmq: 2\r\n" + "rclw: rnzm + wqnn\r\n"
      + "mdpz: 2\r\n" + "qhbj: nrfd * whlb\r\n" + "wsld: csjh + fqrw\r\n" + "gsbf: 3\r\n" + "pnfl: sgqw * vwml\r\n"
      + "sqjj: 6\r\n" + "pqvp: gndz * vwhc\r\n" + "swlt: rppn + zvqs\r\n" + "dhqf: 12\r\n" + "lwbw: 3\r\n"
      + "jsqw: 4\r\n" + "vrfw: 2\r\n" + "thtg: svcl + qrbp\r\n" + "mmcc: 14\r\n" + "cdzm: ddlp + twfs\r\n"
      + "zphc: 13\r\n" + "jpgm: hjnl * lljj\r\n" + "cgpb: 3\r\n" + "fqzw: 2\r\n" + "cfqc: 3\r\n" + "hfwt: 2\r\n"
      + "spcg: 13\r\n" + "vshb: 7\r\n" + "zrdn: gcjm * lnmd\r\n" + "pwwf: tnvc + pgrb\r\n" + "ncsq: 13\r\n"
      + "pllj: 10\r\n" + "pdwq: 3\r\n" + "zfrw: 5\r\n" + "ldfb: mmcj - tsnt\r\n" + "svvq: fmvg * ngns\r\n"
      + "bmcp: vszs / hmjc\r\n" + "plmj: nnqq + hgtt\r\n" + "sggf: tmfs * ndhm\r\n" + "sqng: hbgh + cwcv\r\n"
      + "fbpt: cnvh * pmlz\r\n" + "tfnn: wfqv - gqmv\r\n" + "tqrr: dbwg * dfbp\r\n" + "tsrq: dmrv + rvzf\r\n"
      + "jwsv: hrsh + jrrw\r\n" + "qfgd: 1\r\n" + "nmwz: vjfl - qcvb\r\n" + "qhtf: 9\r\n" + "pcgj: 2\r\n"
      + "mgwm: 4\r\n" + "tsmp: rvrd + rzvg\r\n" + "jrpp: fnml / ldmq\r\n" + "tllq: sdgq * qtqb\r\n" + "vgjl: 9\r\n"
      + "vwml: 13\r\n" + "bnns: 2\r\n" + "nnvm: 7\r\n" + "ngjw: 6\r\n" + "bhzh: tqcl + vblj\r\n" + "bstr: 5\r\n"
      + "zvgv: fzvq + sgjw\r\n" + "zsld: ttlz + cgpf\r\n" + "gwhn: 11\r\n" + "nnqb: 8\r\n" + "rhzt: 5\r\n"
      + "fbdp: svpq + gcdv\r\n" + "sdgq: qwjs - rgld\r\n" + "dpln: 5\r\n" + "ljmb: cbsj + mjms\r\n"
      + "cbbh: frbm + ptcv\r\n" + "vvjl: gglp + fdzs\r\n" + "qrbp: 3\r\n" + "rhzw: 8\r\n" + "hcsc: lqpg * qvwt\r\n"
      + "vvps: vwqb * gbtl\r\n" + "rhwl: 11\r\n" + "bcdl: 4\r\n" + "mjzz: dlcm * fbtt\r\n" + "glnf: 2\r\n"
      + "mrqq: 2\r\n" + "dgjt: 4\r\n" + "sqdm: 3\r\n" + "whbs: 5\r\n" + "gzmq: tmsf * fnqs\r\n"
      + "dqnf: crvs + vjhq\r\n" + "csjm: znlj + cqlc\r\n" + "wsml: snct * ppnb\r\n" + "ggfp: 2\r\n"
      + "mzpg: wlts + jfch\r\n" + "wgnd: 3\r\n" + "zmtn: dwfw * sqng\r\n" + "grmd: 4\r\n" + "frhs: 4\r\n"
      + "lwbr: tqgz + psrc\r\n" + "ssjp: 5\r\n" + "ndqh: 2\r\n" + "qszd: 3\r\n" + "qtvt: 3\r\n"
      + "hpbd: vfzj * dcsd\r\n" + "vfsf: pdsg * frsp\r\n" + "htjj: 3\r\n" + "qtrp: hmsn * vtzl\r\n"
      + "csfn: sgvf + plpb\r\n" + "hsgp: ljgq * scwf\r\n" + "qbnc: hqzf + fwfl\r\n" + "qnbd: 2\r\n" + "tjrz: 3\r\n"
      + "cdbm: 1\r\n" + "sqlv: 3\r\n" + "tlfs: 4\r\n" + "vszb: gnbz + vslw\r\n" + "bvll: qwhm * pdjf\r\n"
      + "qgnz: 1\r\n" + "ffbh: trpv / bnvc\r\n" + "htvr: gtgs + nwlj\r\n" + "ztrt: hfgs * vcpt\r\n" + "pqzr: 13\r\n"
      + "bcjf: twzg * hfbj\r\n" + "qnlg: rhlm + hppm\r\n" + "sqdv: 3\r\n" + "wszc: 2\r\n" + "jzjg: rqqn * nvhl\r\n"
      + "mmlz: ggtf * rpzr\r\n" + "vlhd: 7\r\n" + "wpvh: 5\r\n" + "trtj: jsmt * sfzs\r\n" + "nvfz: zbfz * mfzw\r\n"
      + "mgvv: vtcg + rhdt\r\n" + "rgld: 4\r\n" + "npnl: djrv * mbhf\r\n" + "rrsz: 2\r\n" + "qpcj: 4\r\n"
      + "hptv: pvsp + rtcs\r\n" + "tfzg: zlch * wqmd\r\n" + "hcdp: wzhh + lvlf\r\n" + "fmrz: 3\r\n"
      + "qdrh: fjnp + hzfs\r\n" + "ntqg: jpnb - llzs\r\n" + "fmqf: 5\r\n" + "ptnc: 2\r\n" + "nrcj: nfjv * clrd\r\n"
      + "shjz: 4\r\n" + "hdnw: frwq + gphl\r\n" + "wvst: 7\r\n" + "mzdb: 6\r\n" + "pgnv: thpm + cffl\r\n"
      + "mnsg: zrhn + bfpp\r\n" + "fthb: 2\r\n" + "pznp: 2\r\n" + "vwnj: 5\r\n" + "whng: 4\r\n" + "dbmz: 4\r\n"
      + "glst: nmfn + tdbw\r\n" + "rrvr: bvwq + fvzh\r\n" + "jttb: mtdl / vrrt\r\n" + "vctc: rjqp * cwpq\r\n"
      + "nrtr: 9\r\n" + "gqqs: 3\r\n" + "pbpb: 4\r\n" + "szqj: mbbz * fwgp\r\n" + "wbpw: pznh * zwbh\r\n"
      + "hqzf: ldmt * vdwv\r\n" + "fpgt: 1\r\n" + "fwgp: 2\r\n" + "rvnf: 1\r\n" + "qcfb: 4\r\n"
      + "pwzw: wttp + cfbs\r\n" + "dwdp: hsmc * vqwm\r\n" + "cgld: wglm - mqmv\r\n" + "pmrv: 3\r\n"
      + "tmmd: qtvt * ltmn\r\n" + "ddtf: grbb * tjfp\r\n" + "csqh: 3\r\n" + "rtpg: 2\r\n" + "btrl: 5\r\n"
      + "hrnj: jwsv * qnbd\r\n" + "ggmm: 5\r\n" + "wfmp: dzfg * wnzn\r\n" + "lplj: scsl * ggpv\r\n"
      + "rshp: jfjr * hccw\r\n" + "gdmz: 2\r\n" + "rjbv: 5\r\n" + "ztgb: dcbz * lhpq\r\n" + "whtj: 3\r\n"
      + "hnqq: wlpp / stmn\r\n" + "tcbv: gbpf * jqbg\r\n" + "cvtm: ghtr * phmw\r\n" + "wgtz: 7\r\n"
      + "thfb: vfzg + pjhf\r\n" + "nclh: 5\r\n" + "ddth: 6\r\n" + "ghgb: fhzz + pcrg\r\n" + "hdlf: 13\r\n"
      + "cwnj: qlhp * mdnw\r\n" + "ztsv: sstl + rwwq\r\n" + "lvlf: wffw + jdtz\r\n" + "fnbt: hgdn * rmdw\r\n"
      + "pbhl: 17\r\n" + "cprt: 7\r\n" + "hbgh: 4\r\n" + "sznn: 1\r\n" + "vcwr: 5\r\n" + "vhbr: 2\r\n" + "zhnv: 7\r\n"
      + "ljbw: 16\r\n" + "ftrm: msvj - hzvr\r\n" + "zpbq: 12\r\n" + "vtfr: rtmq * wpvh\r\n" + "lzcm: tbsm + fmfq\r\n"
      + "ddlp: 12\r\n" + "mdzc: 6\r\n" + "bzjl: dqcv * zhnv\r\n" + "lvrl: 3\r\n" + "mbtd: 11\r\n" + "lfqt: 6\r\n"
      + "wnhl: 3\r\n" + "hnmn: 2\r\n" + "bgqv: 14\r\n" + "vczz: vbbm * rvrm\r\n" + "ccsp: nvpv + bsmq\r\n"
      + "lqtf: 5\r\n" + "fnhz: htzp + fzgm\r\n" + "gmhq: mlzh - mcpd\r\n" + "mqss: ddtf * fdpf\r\n"
      + "wtlh: rqhw * jjqm\r\n" + "flnr: glln * gwbq\r\n" + "bgnn: 3\r\n" + "hpgr: 14\r\n" + "ftjz: 1\r\n"
      + "wqmd: glcq + blwg\r\n" + "wmbj: pjts * tmjs\r\n" + "fjlw: 5\r\n" + "twvz: 12\r\n" + "qsls: 16\r\n"
      + "mjrn: 2\r\n" + "mfds: 6\r\n" + "sgvf: 5\r\n" + "drbm: vzcn + hsdq\r\n" + "bfhc: 12\r\n" + "vlnn: 9\r\n"
      + "snlm: tswc * plmj\r\n" + "jscj: sznn + gwsr\r\n" + "qlbt: 4\r\n" + "mptv: nwtn + cplw\r\n" + "fjcs: 6\r\n"
      + "lffh: 3\r\n" + "zjgj: 14\r\n" + "zvwd: dmwz * ndvd\r\n" + "bqbl: lcqh * wbjq\r\n" + "trfn: tbhl + qpvl\r\n"
      + "fvvg: slhn + fzwl\r\n" + "psjl: lwrd * hzhb\r\n" + "qmrn: 2\r\n" + "pvtz: pzrz * rfgp\r\n" + "sdmj: 13\r\n"
      + "qvlh: 4\r\n" + "zlnr: 3\r\n" + "pzhv: 5\r\n" + "hlvd: 5\r\n" + "cvzl: 4\r\n" + "pmhg: hhpq * rswt\r\n"
      + "vcfr: hlvd * npjw\r\n" + "zjpn: 2\r\n" + "gbvc: gvnr - zfqr\r\n" + "qwpt: 3\r\n" + "qgsd: 3\r\n"
      + "lpjh: tpqj + cbmf\r\n" + "rppn: 2\r\n" + "rpvt: 2\r\n" + "scqc: 4\r\n" + "zphb: pjjj * mvhq\r\n"
      + "grmn: vhbr * rppb\r\n" + "znvv: gsfz + vhzh\r\n" + "swvm: 1\r\n" + "wgrz: wjcv + zwvp\r\n" + "pcmv: 3\r\n"
      + "vlzg: 3\r\n" + "lnwr: 9\r\n" + "dbpj: nwfz * fjhb\r\n" + "gmwb: 3\r\n" + "tfcl: 10\r\n" + "tlws: 3\r\n"
      + "fzdd: 4\r\n" + "brjm: grzd + mzwd\r\n" + "stcq: 3\r\n" + "lptf: 10\r\n" + "lbnr: 5\r\n" + "bcqw: 10\r\n"
      + "hwqp: shrn - znch\r\n" + "jbrh: fpgt + bswt\r\n" + "prrw: pzhv * wnjd\r\n" + "qlvz: 12\r\n" + "jdtm: 2\r\n"
      + "cjgn: vddj + jnpf\r\n" + "cslt: pwsp + svvq\r\n" + "hpjh: jjbd + wvpp\r\n" + "tjhb: rflj + mwmv\r\n"
      + "jfqw: 8\r\n" + "bfml: ctwv + fplv\r\n" + "mwmv: 1\r\n" + "fqzg: nqvp + bnmm\r\n" + "fpmw: 2\r\n"
      + "mpwt: 8\r\n" + "jcpc: 1\r\n" + "twjs: 2\r\n" + "vzpq: jlwn + bcsf\r\n" + "hrfj: 2\r\n" + "jhnh: 11\r\n"
      + "wzmz: vqjg * fnhz\r\n" + "nsvt: 4\r\n" + "vqzz: 2\r\n" + "snct: 3\r\n" + "sssd: 2\r\n"
      + "jbmc: smfr * vzzv\r\n" + "wqsh: rsnp * zvfg\r\n" + "jpqm: bczt + wbql\r\n" + "crvt: hfcm - hcdp\r\n"
      + "dnjq: qnlq + brpf\r\n" + "nwtn: 2\r\n" + "dvtl: scmn + ppgj\r\n" + "fjnp: qzvc / dfjb\r\n"
      + "rvmj: nndq * hfvz\r\n" + "plrm: 2\r\n" + "ncrl: 4\r\n" + "tpfd: 3\r\n" + "fjqb: tjqf * jqjz\r\n"
      + "vwfs: 15\r\n" + "zvmg: bcdl * jbws\r\n" + "jllm: 4\r\n" + "cgzj: jdtm + lzjw\r\n" + "gdzw: zftv * jgcz\r\n"
      + "mgpd: 5\r\n" + "cwcv: pmdj * jtfh\r\n" + "ggql: 14\r\n" + "vzlj: 2\r\n" + "brrz: 5\r\n"
      + "sqwv: jqmb + rwwp\r\n" + "djzf: dlrc * jtvz\r\n" + "nrfd: sgfn * tmhw\r\n" + "sbcf: 9\r\n"
      + "slhn: wzsb - cqvw\r\n" + "thws: 3\r\n" + "jglj: vgrf + pfgq\r\n" + "hrzg: 11\r\n" + "rszz: jrzf + sgdt\r\n"
      + "mrfw: 3\r\n" + "ldnz: hptv / zndn\r\n" + "cnph: 4\r\n" + "rbgt: 4\r\n" + "jpgp: 5\r\n"
      + "czds: cmqw * jlcz\r\n" + "tbhl: htqn * bmnj\r\n" + "jjfl: 2\r\n" + "sbrq: 1\r\n" + "rvcj: 7\r\n"
      + "hccw: jbjs + bbnf\r\n" + "ttgj: pltl + hhcq\r\n" + "pjjm: 10\r\n" + "sqdb: tltc - jcww\r\n" + "bshd: 2\r\n"
      + "svgw: zrlg + wllz\r\n" + "crnh: 3\r\n" + "nqrj: 3\r\n" + "qvfg: 4\r\n" + "cmwf: lntg * vwmb\r\n"
      + "jmps: 5\r\n" + "qwfl: cglv * jvqg\r\n" + "fwnw: 3\r\n" + "wbtw: hdth * zrlw\r\n" + "pslb: cmpt / twjs\r\n"
      + "sscl: mptv * cfbd\r\n" + "nwrg: 2\r\n" + "hwzd: 14\r\n" + "zvvb: hprq * hdjf\r\n" + "gfcc: 4\r\n"
      + "tnjc: 1\r\n" + "fnqs: dfwc * zjpn\r\n" + "zfrt: tqfm - lwst\r\n" + "tnth: qvth * zcmj\r\n" + "blhf: 15\r\n"
      + "qnjp: 2\r\n" + "mlnh: lntf * slfr\r\n" + "pmcf: 4\r\n" + "zzhn: gjhp * vwdq\r\n" + "dfzf: 6\r\n"
      + "mnbl: cgtv + rclw\r\n" + "qpgn: csqh * zzhn\r\n" + "lflt: qnsv - ffbh\r\n" + "rrtg: qvlh * lvch\r\n"
      + "zhcg: dvhd * mrcb\r\n" + "bwrv: qpwh * sffw\r\n" + "qvhm: rjjp + pczc\r\n" + "shtp: nrtr * mwtl\r\n"
      + "fwnb: 4\r\n" + "lnbh: 3\r\n" + "zjjw: zljm + cwlr\r\n" + "lctz: htjj * ptjd\r\n" + "mzqf: dmzh + wmbj\r\n"
      + "fqnw: cpcz + cwfh\r\n" + "gbjj: bshd + jwfd\r\n" + "jcwp: wzqb * bbvt\r\n" + "jtvz: crfl + fzdd\r\n"
      + "qcvb: 2\r\n" + "gnzh: qtrp + bfbf\r\n" + "dgjm: sddm + fvfr\r\n" + "gtpq: 5\r\n" + "hfqq: zqjj * nhdg\r\n"
      + "svmd: 5\r\n" + "lcnj: pjhc + swvm\r\n" + "dvrt: rvbr + fcls\r\n" + "qnhv: 10\r\n" + "tfzh: 2\r\n"
      + "glcg: fqrt * mpdz\r\n" + "mnms: 2\r\n" + "nfqr: 7\r\n" + "smml: 15\r\n" + "bwbd: 5\r\n"
      + "zhjb: lzrn + zlfb\r\n" + "vlrw: hqpz + csbv\r\n" + "fpcj: 4\r\n" + "whpb: vrpz * ldfd\r\n"
      + "tfqt: lwbr * cznw\r\n" + "nbmf: wqrc * hfjr\r\n" + "plmm: nrjd * zfsz\r\n" + "bhwb: rdzw * sggg\r\n"
      + "plcq: sglf * mpqp\r\n" + "qsnr: 4\r\n" + "bdgp: tgsd / wqsn\r\n" + "ccgc: 4\r\n" + "hnpv: 2\r\n"
      + "wjhh: 3\r\n" + "qjgz: bgbf - qsjj\r\n" + "rqhq: sjjs + phwt\r\n" + "chtl: 2\r\n" + "tvff: 2\r\n"
      + "cbbb: dwtb * bvtd\r\n" + "hgdn: 3\r\n" + "gbtl: 12\r\n" + "qrgh: 2\r\n" + "hnpr: 1\r\n" + "rwjb: 7\r\n"
      + "pmhh: whpb + qdtj\r\n" + "jnpf: 9\r\n" + "drjb: 11\r\n" + "ltzr: sbpg + ldcr\r\n" + "qdsb: 1\r\n"
      + "zqrs: 13\r\n" + "zlld: 2\r\n" + "hbzt: 2\r\n" + "hmzq: 3\r\n" + "cpvv: 3\r\n" + "rtjr: cbvr + bdbh\r\n"
      + "jfjr: 4\r\n" + "bdwg: vmmd * ntzh\r\n" + "vzvb: mdpw * hzjw\r\n" + "msvj: llqg * ptlp\r\n"
      + "jvpm: drcc * zqcw\r\n" + "jtfh: 11\r\n" + "tctc: nnwn - sfbr\r\n" + "wzqb: rbsz * rmqp\r\n"
      + "cbdd: qttf * pvsf\r\n" + "slrs: rzcn + vrtf\r\n" + "fdzh: 4\r\n" + "nrjs: mcbr * nwbr\r\n" + "wvlm: 15\r\n"
      + "dwfw: lgwg + tqrr\r\n" + "wmfz: cstd * hhmw\r\n" + "qdzq: blhf + glmn\r\n" + "jhsp: 6\r\n" + "wbwv: 3\r\n"
      + "dcsd: 2\r\n" + "zbfq: 2\r\n" + "btdv: dvrt + zjjg\r\n" + "nwbr: 4\r\n" + "gsbq: vrjv + jcjd\r\n"
      + "jnzm: bpcr * lnnt\r\n" + "mtqj: vfvp + zbpb\r\n" + "twcf: gdpm + rpsl\r\n" + "scdn: 5\r\n" + "vmvp: 2\r\n"
      + "hjsb: 3\r\n" + "lwmf: 2\r\n" + "tnhv: 15\r\n" + "lchn: 3\r\n" + "qvdf: 2\r\n" + "sbpf: qhhc * pbhl\r\n"
      + "cdpp: btwf + hpzv\r\n" + "pdsg: 3\r\n" + "hgfq: 2\r\n" + "wfwh: 6\r\n" + "zqgc: srvt + hczp\r\n"
      + "ngmh: 5\r\n" + "mbwm: qjqf - sdmf\r\n" + "tspq: fsnw + nvcm\r\n" + "nszj: 5\r\n" + "nvrl: dgvm + blwl\r\n"
      + "lhst: 4\r\n" + "fsjz: 4\r\n" + "rwqs: zrgb * rzjh\r\n" + "wgtd: 10\r\n" + "vtbn: 3\r\n"
      + "jhbw: bhqq + fvgq\r\n" + "vshp: 8\r\n" + "rncq: 7\r\n" + "tgdl: 5\r\n" + "rtld: 2\r\n" + "slvg: 5\r\n"
      + "gdmw: cslt - mspg\r\n" + "nnnv: fstr * chvd\r\n" + "tsnt: nrjs * vfws\r\n" + "vvpf: 11\r\n"
      + "lzqw: chvz + hrhd";
}
