package at.mschreiber.adventofcode;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Stack;
public class Day5Exercise1 {
	
	public static void main(String args[]) {
		String[] lines = input.split("\r\n");
		int score = 0;
		
//		"	               [M]     [V]     [L]\r\n"
//		+ "[G]             [V] [C] [G]     [D]\r\n"
//		+ "[J]             [Q] [W] [Z] [C] [J]\r\n"
//		+ "[W]         [W] [G] [V] [D] [G] [C]\r\n"
//		+ "[R]     [G] [N] [B] [D] [C] [M] [W]\r\n"
//		+ "[F] [M] [H] [C] [S] [T] [N] [N] [N]\r\n"
//		+ "[T] [W] [N] [R] [F] [R] [B] [J] [P]\r\n"
//		+ "[Z] [G] [J] [J] [W] [S] [H] [S] [G]";
		
		Stack<String> stack1 = new Stack<String>();
		Stack<String> stack2 = new Stack<String>();
		Stack<String> stack3 = new Stack<String>();
		Stack<String> stack4 = new Stack<String>();
		Stack<String> stack5 = new Stack<String>();
		Stack<String> stack6 = new Stack<String>();
		Stack<String> stack7 = new Stack<String>();
		Stack<String> stack8 = new Stack<String>();
		Stack<String> stack9 = new Stack<String>();

		stack1.push("Z");
		stack1.push("T");
		stack1.push("F");
		stack1.push("R");
		stack1.push("W");
		stack1.push("J");
		stack1.push("G");
		
		stack2.push("G");
		stack2.push("W");
		stack2.push("M");
		
		stack3.push("J");
		stack3.push("N");
		stack3.push("H");
		stack3.push("G");
		
		stack4.push("J");
		stack4.push("R");
		stack4.push("C");
		stack4.push("N");
		stack4.push("W");
		
		stack5.push("W");
		stack5.push("F");
		stack5.push("S");
		stack5.push("B");
		stack5.push("G");
		stack5.push("Q");
		stack5.push("V");
		stack5.push("M");
		
		stack6.push("S");
		stack6.push("R");
		stack6.push("T");
		stack6.push("D");
		stack6.push("V");
		stack6.push("W");
		stack6.push("C");
		
		stack7.push("H");
		stack7.push("B");
		stack7.push("N");
		stack7.push("C");
		stack7.push("D");
		stack7.push("Z");
		stack7.push("G");
		stack7.push("V");
		
		stack8.push("S");
		stack8.push("J");
		stack8.push("N");
		stack8.push("M");
		stack8.push("G");
		stack8.push("C");
		
		stack9.push("G");
		stack9.push("P");
		stack9.push("N");
		stack9.push("W");
		stack9.push("C");
		stack9.push("J");
		stack9.push("D");
		stack9.push("L");
		
		List<Stack<String>> stacks = Arrays.asList(stack1, stack2, stack3, stack4, stack5, stack6, stack7, stack8, stack9);
		for (String line : lines) {
			int count = Integer.parseInt(line.split(" ")[1]);
			int from = Integer.parseInt(line.split(" ")[3]);
			int to = Integer.parseInt(line.split(" ")[5]);
			Stack<String> fromStack = stacks.get(from  -1 );
			Stack<String> toStack = stacks.get(to -1);
			for (int i = 0; i < count; i++) {
				toStack.push(fromStack.pop());
			}
		}
		for (Stack<String> stack : stacks) {
			System.out.print(stack.peek());
		}
	}

	
	public static String input = "move 1 from 5 to 2\r\n"
			+ "move 7 from 7 to 1\r\n"
			+ "move 1 from 1 to 7\r\n"
			+ "move 1 from 4 to 1\r\n"
			+ "move 7 from 9 to 1\r\n"
			+ "move 1 from 3 to 7\r\n"
			+ "move 4 from 5 to 4\r\n"
			+ "move 6 from 4 to 9\r\n"
			+ "move 2 from 7 to 6\r\n"
			+ "move 6 from 8 to 2\r\n"
			+ "move 2 from 4 to 5\r\n"
			+ "move 2 from 3 to 7\r\n"
			+ "move 11 from 1 to 4\r\n"
			+ "move 6 from 6 to 1\r\n"
			+ "move 3 from 5 to 3\r\n"
			+ "move 5 from 9 to 8\r\n"
			+ "move 1 from 2 to 3\r\n"
			+ "move 2 from 7 to 9\r\n"
			+ "move 7 from 1 to 2\r\n"
			+ "move 1 from 5 to 3\r\n"
			+ "move 1 from 5 to 3\r\n"
			+ "move 5 from 8 to 5\r\n"
			+ "move 3 from 5 to 4\r\n"
			+ "move 1 from 1 to 7\r\n"
			+ "move 1 from 3 to 8\r\n"
			+ "move 2 from 6 to 3\r\n"
			+ "move 3 from 3 to 4\r\n"
			+ "move 1 from 6 to 2\r\n"
			+ "move 5 from 4 to 2\r\n"
			+ "move 2 from 5 to 3\r\n"
			+ "move 2 from 7 to 1\r\n"
			+ "move 1 from 8 to 1\r\n"
			+ "move 7 from 1 to 7\r\n"
			+ "move 4 from 4 to 2\r\n"
			+ "move 7 from 4 to 1\r\n"
			+ "move 10 from 1 to 5\r\n"
			+ "move 10 from 5 to 2\r\n"
			+ "move 11 from 2 to 3\r\n"
			+ "move 1 from 1 to 6\r\n"
			+ "move 1 from 4 to 7\r\n"
			+ "move 4 from 7 to 1\r\n"
			+ "move 6 from 2 to 5\r\n"
			+ "move 2 from 1 to 3\r\n"
			+ "move 1 from 9 to 5\r\n"
			+ "move 2 from 9 to 6\r\n"
			+ "move 1 from 6 to 1\r\n"
			+ "move 3 from 5 to 4\r\n"
			+ "move 20 from 3 to 9\r\n"
			+ "move 3 from 7 to 1\r\n"
			+ "move 3 from 5 to 2\r\n"
			+ "move 3 from 4 to 8\r\n"
			+ "move 3 from 1 to 3\r\n"
			+ "move 3 from 1 to 2\r\n"
			+ "move 2 from 6 to 1\r\n"
			+ "move 10 from 9 to 6\r\n"
			+ "move 6 from 6 to 7\r\n"
			+ "move 4 from 6 to 3\r\n"
			+ "move 11 from 2 to 6\r\n"
			+ "move 1 from 8 to 9\r\n"
			+ "move 13 from 2 to 3\r\n"
			+ "move 1 from 1 to 9\r\n"
			+ "move 1 from 9 to 4\r\n"
			+ "move 1 from 8 to 2\r\n"
			+ "move 1 from 8 to 2\r\n"
			+ "move 4 from 7 to 8\r\n"
			+ "move 8 from 6 to 9\r\n"
			+ "move 3 from 2 to 3\r\n"
			+ "move 3 from 8 to 4\r\n"
			+ "move 11 from 9 to 2\r\n"
			+ "move 7 from 9 to 6\r\n"
			+ "move 1 from 1 to 5\r\n"
			+ "move 4 from 4 to 9\r\n"
			+ "move 21 from 3 to 1\r\n"
			+ "move 1 from 3 to 9\r\n"
			+ "move 7 from 6 to 3\r\n"
			+ "move 6 from 1 to 2\r\n"
			+ "move 13 from 1 to 5\r\n"
			+ "move 2 from 1 to 2\r\n"
			+ "move 3 from 9 to 3\r\n"
			+ "move 2 from 2 to 3\r\n"
			+ "move 2 from 6 to 4\r\n"
			+ "move 3 from 3 to 5\r\n"
			+ "move 13 from 5 to 2\r\n"
			+ "move 5 from 3 to 4\r\n"
			+ "move 2 from 7 to 9\r\n"
			+ "move 2 from 4 to 2\r\n"
			+ "move 1 from 3 to 8\r\n"
			+ "move 1 from 6 to 1\r\n"
			+ "move 4 from 3 to 7\r\n"
			+ "move 2 from 5 to 7\r\n"
			+ "move 1 from 7 to 2\r\n"
			+ "move 1 from 5 to 9\r\n"
			+ "move 4 from 7 to 8\r\n"
			+ "move 1 from 1 to 9\r\n"
			+ "move 6 from 8 to 1\r\n"
			+ "move 4 from 4 to 8\r\n"
			+ "move 25 from 2 to 9\r\n"
			+ "move 1 from 4 to 3\r\n"
			+ "move 1 from 3 to 7\r\n"
			+ "move 4 from 8 to 1\r\n"
			+ "move 1 from 7 to 4\r\n"
			+ "move 3 from 1 to 6\r\n"
			+ "move 5 from 2 to 1\r\n"
			+ "move 1 from 5 to 1\r\n"
			+ "move 1 from 4 to 1\r\n"
			+ "move 24 from 9 to 6\r\n"
			+ "move 9 from 1 to 6\r\n"
			+ "move 1 from 5 to 6\r\n"
			+ "move 1 from 1 to 9\r\n"
			+ "move 1 from 2 to 8\r\n"
			+ "move 1 from 8 to 1\r\n"
			+ "move 3 from 1 to 8\r\n"
			+ "move 36 from 6 to 3\r\n"
			+ "move 2 from 7 to 3\r\n"
			+ "move 1 from 2 to 5\r\n"
			+ "move 1 from 5 to 2\r\n"
			+ "move 1 from 6 to 2\r\n"
			+ "move 10 from 3 to 2\r\n"
			+ "move 3 from 8 to 2\r\n"
			+ "move 1 from 1 to 7\r\n"
			+ "move 2 from 2 to 6\r\n"
			+ "move 10 from 9 to 1\r\n"
			+ "move 2 from 6 to 4\r\n"
			+ "move 13 from 3 to 4\r\n"
			+ "move 8 from 3 to 7\r\n"
			+ "move 8 from 1 to 2\r\n"
			+ "move 5 from 3 to 8\r\n"
			+ "move 3 from 1 to 9\r\n"
			+ "move 1 from 7 to 1\r\n"
			+ "move 7 from 4 to 5\r\n"
			+ "move 1 from 1 to 2\r\n"
			+ "move 14 from 2 to 6\r\n"
			+ "move 2 from 7 to 2\r\n"
			+ "move 8 from 4 to 8\r\n"
			+ "move 3 from 7 to 9\r\n"
			+ "move 2 from 9 to 8\r\n"
			+ "move 2 from 7 to 1\r\n"
			+ "move 1 from 7 to 8\r\n"
			+ "move 1 from 6 to 8\r\n"
			+ "move 1 from 9 to 3\r\n"
			+ "move 4 from 2 to 7\r\n"
			+ "move 6 from 6 to 1\r\n"
			+ "move 3 from 1 to 9\r\n"
			+ "move 1 from 1 to 7\r\n"
			+ "move 6 from 5 to 6\r\n"
			+ "move 1 from 5 to 2\r\n"
			+ "move 1 from 6 to 8\r\n"
			+ "move 5 from 7 to 5\r\n"
			+ "move 1 from 2 to 9\r\n"
			+ "move 2 from 3 to 4\r\n"
			+ "move 9 from 8 to 4\r\n"
			+ "move 8 from 4 to 8\r\n"
			+ "move 6 from 6 to 7\r\n"
			+ "move 5 from 6 to 4\r\n"
			+ "move 7 from 9 to 7\r\n"
			+ "move 7 from 8 to 7\r\n"
			+ "move 5 from 8 to 4\r\n"
			+ "move 3 from 1 to 6\r\n"
			+ "move 1 from 2 to 7\r\n"
			+ "move 1 from 1 to 4\r\n"
			+ "move 4 from 5 to 2\r\n"
			+ "move 2 from 6 to 9\r\n"
			+ "move 1 from 3 to 7\r\n"
			+ "move 1 from 5 to 1\r\n"
			+ "move 1 from 8 to 9\r\n"
			+ "move 1 from 6 to 1\r\n"
			+ "move 1 from 2 to 7\r\n"
			+ "move 2 from 8 to 1\r\n"
			+ "move 2 from 1 to 8\r\n"
			+ "move 3 from 2 to 4\r\n"
			+ "move 1 from 6 to 1\r\n"
			+ "move 17 from 4 to 1\r\n"
			+ "move 3 from 2 to 7\r\n"
			+ "move 13 from 7 to 8\r\n"
			+ "move 1 from 2 to 6\r\n"
			+ "move 14 from 1 to 4\r\n"
			+ "move 2 from 8 to 5\r\n"
			+ "move 1 from 9 to 7\r\n"
			+ "move 2 from 5 to 4\r\n"
			+ "move 1 from 9 to 3\r\n"
			+ "move 5 from 1 to 5\r\n"
			+ "move 3 from 4 to 1\r\n"
			+ "move 1 from 3 to 2\r\n"
			+ "move 7 from 4 to 5\r\n"
			+ "move 9 from 7 to 8\r\n"
			+ "move 5 from 4 to 2\r\n"
			+ "move 1 from 1 to 3\r\n"
			+ "move 1 from 9 to 2\r\n"
			+ "move 15 from 8 to 6\r\n"
			+ "move 1 from 3 to 7\r\n"
			+ "move 11 from 6 to 5\r\n"
			+ "move 1 from 4 to 8\r\n"
			+ "move 3 from 1 to 7\r\n"
			+ "move 5 from 7 to 5\r\n"
			+ "move 27 from 5 to 1\r\n"
			+ "move 8 from 8 to 4\r\n"
			+ "move 1 from 2 to 6\r\n"
			+ "move 3 from 6 to 1\r\n"
			+ "move 9 from 1 to 5\r\n"
			+ "move 5 from 5 to 7\r\n"
			+ "move 2 from 2 to 1\r\n"
			+ "move 2 from 5 to 4\r\n"
			+ "move 6 from 7 to 6\r\n"
			+ "move 1 from 5 to 2\r\n"
			+ "move 1 from 7 to 8\r\n"
			+ "move 4 from 6 to 8\r\n"
			+ "move 5 from 6 to 3\r\n"
			+ "move 1 from 7 to 1\r\n"
			+ "move 5 from 4 to 3\r\n"
			+ "move 6 from 8 to 2\r\n"
			+ "move 1 from 7 to 8\r\n"
			+ "move 2 from 8 to 9\r\n"
			+ "move 10 from 3 to 5\r\n"
			+ "move 9 from 5 to 2\r\n"
			+ "move 3 from 4 to 8\r\n"
			+ "move 1 from 5 to 7\r\n"
			+ "move 2 from 9 to 7\r\n"
			+ "move 2 from 8 to 3\r\n"
			+ "move 1 from 3 to 8\r\n"
			+ "move 19 from 1 to 7\r\n"
			+ "move 4 from 2 to 7\r\n"
			+ "move 2 from 4 to 3\r\n"
			+ "move 3 from 3 to 2\r\n"
			+ "move 2 from 8 to 3\r\n"
			+ "move 2 from 5 to 8\r\n"
			+ "move 1 from 2 to 3\r\n"
			+ "move 2 from 8 to 3\r\n"
			+ "move 5 from 2 to 5\r\n"
			+ "move 9 from 7 to 5\r\n"
			+ "move 13 from 5 to 9\r\n"
			+ "move 7 from 2 to 6\r\n"
			+ "move 2 from 6 to 9\r\n"
			+ "move 1 from 2 to 1\r\n"
			+ "move 5 from 6 to 7\r\n"
			+ "move 1 from 5 to 7\r\n"
			+ "move 6 from 1 to 2\r\n"
			+ "move 5 from 3 to 6\r\n"
			+ "move 6 from 7 to 2\r\n"
			+ "move 3 from 6 to 4\r\n"
			+ "move 3 from 7 to 4\r\n"
			+ "move 12 from 7 to 6\r\n"
			+ "move 5 from 4 to 1\r\n"
			+ "move 2 from 7 to 4\r\n"
			+ "move 3 from 4 to 6\r\n"
			+ "move 16 from 6 to 3\r\n"
			+ "move 4 from 1 to 4\r\n"
			+ "move 1 from 1 to 9\r\n"
			+ "move 3 from 9 to 2\r\n"
			+ "move 1 from 4 to 6\r\n"
			+ "move 9 from 3 to 7\r\n"
			+ "move 2 from 6 to 3\r\n"
			+ "move 3 from 3 to 9\r\n"
			+ "move 15 from 2 to 7\r\n"
			+ "move 19 from 7 to 4\r\n"
			+ "move 15 from 9 to 2\r\n"
			+ "move 16 from 2 to 8\r\n"
			+ "move 6 from 3 to 5\r\n"
			+ "move 4 from 7 to 5\r\n"
			+ "move 15 from 8 to 7\r\n"
			+ "move 19 from 4 to 2\r\n"
			+ "move 1 from 8 to 3\r\n"
			+ "move 16 from 2 to 1\r\n"
			+ "move 9 from 7 to 6\r\n"
			+ "move 7 from 2 to 8\r\n"
			+ "move 2 from 2 to 7\r\n"
			+ "move 1 from 9 to 5\r\n"
			+ "move 1 from 3 to 4\r\n"
			+ "move 6 from 1 to 2\r\n"
			+ "move 8 from 5 to 1\r\n"
			+ "move 1 from 5 to 1\r\n"
			+ "move 18 from 1 to 8\r\n"
			+ "move 7 from 7 to 5\r\n"
			+ "move 7 from 5 to 3\r\n"
			+ "move 4 from 3 to 6\r\n"
			+ "move 13 from 8 to 5\r\n"
			+ "move 12 from 8 to 1\r\n"
			+ "move 5 from 1 to 6\r\n"
			+ "move 15 from 5 to 4\r\n"
			+ "move 1 from 1 to 6\r\n"
			+ "move 12 from 6 to 3\r\n"
			+ "move 8 from 3 to 4\r\n"
			+ "move 2 from 7 to 3\r\n"
			+ "move 9 from 3 to 1\r\n"
			+ "move 5 from 2 to 9\r\n"
			+ "move 16 from 4 to 3\r\n"
			+ "move 10 from 1 to 3\r\n"
			+ "move 2 from 1 to 5\r\n"
			+ "move 1 from 3 to 1\r\n"
			+ "move 5 from 6 to 1\r\n"
			+ "move 4 from 9 to 3\r\n"
			+ "move 1 from 2 to 8\r\n"
			+ "move 1 from 8 to 1\r\n"
			+ "move 1 from 9 to 8\r\n"
			+ "move 2 from 5 to 9\r\n"
			+ "move 9 from 4 to 1\r\n"
			+ "move 3 from 1 to 3\r\n"
			+ "move 2 from 6 to 8\r\n"
			+ "move 3 from 8 to 5\r\n"
			+ "move 2 from 1 to 5\r\n"
			+ "move 2 from 9 to 8\r\n"
			+ "move 1 from 8 to 6\r\n"
			+ "move 2 from 5 to 3\r\n"
			+ "move 19 from 3 to 1\r\n"
			+ "move 2 from 4 to 2\r\n"
			+ "move 1 from 5 to 6\r\n"
			+ "move 2 from 2 to 3\r\n"
			+ "move 1 from 8 to 6\r\n"
			+ "move 8 from 3 to 9\r\n"
			+ "move 6 from 3 to 7\r\n"
			+ "move 2 from 6 to 2\r\n"
			+ "move 1 from 6 to 1\r\n"
			+ "move 1 from 1 to 8\r\n"
			+ "move 1 from 8 to 9\r\n"
			+ "move 1 from 7 to 3\r\n"
			+ "move 19 from 1 to 5\r\n"
			+ "move 21 from 5 to 2\r\n"
			+ "move 13 from 2 to 6\r\n"
			+ "move 13 from 1 to 8\r\n"
			+ "move 7 from 9 to 7\r\n"
			+ "move 2 from 9 to 2\r\n"
			+ "move 10 from 8 to 3\r\n"
			+ "move 1 from 1 to 6\r\n"
			+ "move 10 from 2 to 4\r\n"
			+ "move 11 from 3 to 5\r\n"
			+ "move 8 from 5 to 6\r\n"
			+ "move 1 from 3 to 7\r\n"
			+ "move 2 from 8 to 6\r\n"
			+ "move 2 from 2 to 8\r\n"
			+ "move 3 from 7 to 6\r\n"
			+ "move 2 from 8 to 6\r\n"
			+ "move 1 from 1 to 2\r\n"
			+ "move 24 from 6 to 5\r\n"
			+ "move 2 from 3 to 8\r\n"
			+ "move 1 from 8 to 6\r\n"
			+ "move 7 from 7 to 9\r\n"
			+ "move 4 from 6 to 9\r\n"
			+ "move 1 from 8 to 9\r\n"
			+ "move 21 from 5 to 9\r\n"
			+ "move 2 from 7 to 2\r\n"
			+ "move 1 from 8 to 5\r\n"
			+ "move 1 from 7 to 3\r\n"
			+ "move 12 from 9 to 6\r\n"
			+ "move 6 from 6 to 3\r\n"
			+ "move 12 from 9 to 4\r\n"
			+ "move 4 from 5 to 6\r\n"
			+ "move 13 from 4 to 2\r\n"
			+ "move 8 from 4 to 8\r\n"
			+ "move 10 from 6 to 8\r\n"
			+ "move 11 from 8 to 9\r\n"
			+ "move 4 from 8 to 4\r\n"
			+ "move 2 from 4 to 3\r\n"
			+ "move 8 from 3 to 8\r\n"
			+ "move 2 from 6 to 8\r\n"
			+ "move 1 from 3 to 8\r\n"
			+ "move 6 from 2 to 4\r\n"
			+ "move 1 from 4 to 8\r\n"
			+ "move 1 from 9 to 7\r\n"
			+ "move 13 from 8 to 4\r\n"
			+ "move 1 from 7 to 1\r\n"
			+ "move 1 from 1 to 4\r\n"
			+ "move 8 from 4 to 7\r\n"
			+ "move 3 from 5 to 7\r\n"
			+ "move 19 from 9 to 7\r\n"
			+ "move 3 from 2 to 7\r\n"
			+ "move 1 from 8 to 2\r\n"
			+ "move 13 from 7 to 6\r\n"
			+ "move 1 from 2 to 4\r\n"
			+ "move 4 from 6 to 2\r\n"
			+ "move 1 from 8 to 3\r\n"
			+ "move 7 from 6 to 8\r\n"
			+ "move 1 from 6 to 2\r\n"
			+ "move 1 from 2 to 7\r\n"
			+ "move 9 from 2 to 3\r\n"
			+ "move 1 from 6 to 2\r\n"
			+ "move 21 from 7 to 5\r\n"
			+ "move 9 from 5 to 3\r\n"
			+ "move 19 from 3 to 9\r\n"
			+ "move 5 from 8 to 5\r\n"
			+ "move 2 from 2 to 1\r\n"
			+ "move 2 from 1 to 8\r\n"
			+ "move 6 from 4 to 5\r\n"
			+ "move 3 from 8 to 7\r\n"
			+ "move 15 from 9 to 2\r\n"
			+ "move 2 from 2 to 5\r\n"
			+ "move 3 from 9 to 6\r\n"
			+ "move 5 from 4 to 5\r\n"
			+ "move 11 from 2 to 6\r\n"
			+ "move 1 from 8 to 6\r\n"
			+ "move 1 from 9 to 5\r\n"
			+ "move 1 from 7 to 3\r\n"
			+ "move 6 from 5 to 6\r\n"
			+ "move 1 from 4 to 6\r\n"
			+ "move 1 from 3 to 4\r\n"
			+ "move 13 from 5 to 2\r\n"
			+ "move 16 from 6 to 9\r\n"
			+ "move 4 from 4 to 5\r\n"
			+ "move 2 from 6 to 2\r\n"
			+ "move 2 from 6 to 4\r\n"
			+ "move 2 from 4 to 5\r\n"
			+ "move 2 from 7 to 8\r\n"
			+ "move 2 from 6 to 3\r\n"
			+ "move 2 from 5 to 8\r\n"
			+ "move 14 from 5 to 7\r\n"
			+ "move 4 from 8 to 1\r\n"
			+ "move 4 from 1 to 6\r\n"
			+ "move 1 from 3 to 9\r\n"
			+ "move 1 from 6 to 1\r\n"
			+ "move 2 from 7 to 3\r\n"
			+ "move 2 from 3 to 7\r\n"
			+ "move 2 from 5 to 2\r\n"
			+ "move 9 from 9 to 2\r\n"
			+ "move 13 from 7 to 3\r\n"
			+ "move 12 from 3 to 9\r\n"
			+ "move 2 from 6 to 8\r\n"
			+ "move 14 from 2 to 9\r\n"
			+ "move 2 from 8 to 9\r\n"
			+ "move 10 from 2 to 1\r\n"
			+ "move 1 from 7 to 4\r\n"
			+ "move 2 from 3 to 8\r\n"
			+ "move 4 from 2 to 1\r\n"
			+ "move 1 from 8 to 3\r\n"
			+ "move 1 from 2 to 6\r\n"
			+ "move 1 from 8 to 3\r\n"
			+ "move 4 from 9 to 4\r\n"
			+ "move 1 from 3 to 5\r\n"
			+ "move 1 from 5 to 1\r\n"
			+ "move 1 from 3 to 9\r\n"
			+ "move 12 from 1 to 8\r\n"
			+ "move 10 from 8 to 5\r\n"
			+ "move 7 from 5 to 6\r\n"
			+ "move 1 from 1 to 9\r\n"
			+ "move 3 from 5 to 1\r\n"
			+ "move 1 from 1 to 3\r\n"
			+ "move 16 from 9 to 7\r\n"
			+ "move 4 from 4 to 3\r\n"
			+ "move 1 from 4 to 9\r\n"
			+ "move 15 from 7 to 8\r\n"
			+ "move 15 from 9 to 1\r\n"
			+ "move 8 from 1 to 6\r\n"
			+ "move 1 from 9 to 3\r\n"
			+ "move 17 from 6 to 2\r\n"
			+ "move 1 from 9 to 1\r\n"
			+ "move 15 from 2 to 7\r\n"
			+ "move 14 from 8 to 9\r\n"
			+ "move 12 from 7 to 9\r\n"
			+ "move 12 from 9 to 3\r\n"
			+ "move 3 from 7 to 9\r\n"
			+ "move 1 from 7 to 4\r\n"
			+ "move 7 from 9 to 6\r\n"
			+ "move 1 from 4 to 6\r\n"
			+ "move 11 from 9 to 6\r\n"
			+ "move 2 from 1 to 2\r\n"
			+ "move 18 from 6 to 4\r\n"
			+ "move 4 from 2 to 7\r\n"
			+ "move 2 from 7 to 3\r\n"
			+ "move 2 from 7 to 8\r\n"
			+ "move 4 from 1 to 5\r\n"
			+ "move 1 from 9 to 2\r\n"
			+ "move 2 from 5 to 4\r\n"
			+ "move 5 from 1 to 3\r\n"
			+ "move 2 from 3 to 7\r\n"
			+ "move 2 from 3 to 9\r\n"
			+ "move 1 from 6 to 7\r\n"
			+ "move 1 from 2 to 9\r\n"
			+ "move 2 from 8 to 1\r\n"
			+ "move 3 from 1 to 3\r\n"
			+ "move 2 from 5 to 8\r\n"
			+ "move 2 from 3 to 5\r\n"
			+ "move 1 from 5 to 2\r\n"
			+ "move 1 from 1 to 3\r\n"
			+ "move 1 from 9 to 2\r\n"
			+ "move 1 from 9 to 1\r\n"
			+ "move 3 from 7 to 6\r\n"
			+ "move 1 from 1 to 9\r\n"
			+ "move 2 from 8 to 9\r\n"
			+ "move 1 from 2 to 3\r\n"
			+ "move 2 from 8 to 2\r\n"
			+ "move 2 from 6 to 5\r\n"
			+ "move 1 from 8 to 5\r\n"
			+ "move 3 from 2 to 5\r\n"
			+ "move 3 from 4 to 8\r\n"
			+ "move 1 from 8 to 2\r\n"
			+ "move 3 from 9 to 7\r\n"
			+ "move 3 from 7 to 1\r\n"
			+ "move 1 from 9 to 6\r\n"
			+ "move 3 from 1 to 2\r\n"
			+ "move 2 from 8 to 7\r\n"
			+ "move 2 from 7 to 9\r\n"
			+ "move 2 from 6 to 5\r\n"
			+ "move 3 from 5 to 3\r\n"
			+ "move 1 from 2 to 5\r\n"
			+ "move 3 from 2 to 7\r\n"
			+ "move 2 from 5 to 6\r\n"
			+ "move 15 from 4 to 9\r\n"
			+ "move 1 from 3 to 1\r\n"
			+ "move 25 from 3 to 4\r\n"
			+ "move 3 from 7 to 3\r\n"
			+ "move 5 from 9 to 5\r\n"
			+ "move 10 from 9 to 5\r\n"
			+ "move 9 from 5 to 1\r\n"
			+ "move 5 from 5 to 2\r\n"
			+ "move 1 from 6 to 7\r\n"
			+ "move 5 from 5 to 8";
}
